// SPDX-License-Identifier: MIT
// Generated by generate.py from exact pinned runtime bytes.
include "../getters/Machine.dfy"
module BytecodeRejectExpressionsShort {
  import opened BytecodeGetterMachine
  opaque predicate Matches(code: seq<Byte>) {
    |code| == 17776 &&
    code[0] == 96 &&
    code[1] == 128 &&
    code[2] == 96 &&
    code[3] == 64 &&
    code[4] == 82 &&
    code[5] == 52 &&
    code[6] == 128 &&
    code[7] == 21 &&
    code[8] == 97 &&
    code[9] == 0 &&
    code[10] == 15 &&
    code[11] == 87 &&
    code[15] == 91 &&
    code[16] == 80 &&
    code[17] == 96 &&
    code[18] == 4 &&
    code[19] == 54 &&
    code[20] == 16 &&
    code[21] == 97 &&
    code[22] == 0 &&
    code[23] == 63 &&
    code[24] == 87 &&
    code[63] == 91 &&
    code[64] == 95 &&
    code[65] == 95 &&
    code[66] == 253
  }
  predicate Admitted(value: Word, size: Word) { value == 0 && size < 4 }
  function Destinations(): set<nat> { {15,63} }
  opaque predicate Good(id: nat, state: State, value: Word, size: Word) {
    if id == 0 then state == Running(0,[],[])
    else if id == 1 then state == Running(2,[128],[])
    else if id == 2 then state == Running(4,[128,64],[])
    else if id == 3 then state == Running(5,[],Store([],64,128))
    else if id == 4 then state == Running(6,[value],Store([],64,128))
    else if id == 5 then state == Running(7,[value,value],Store([],64,128))
    else if id == 6 then state == Running(8,[value,1],Store([],64,128))
    else if id == 7 then state == Running(11,[value,1,15],Store([],64,128))
    else if id == 8 then state == Running(15,[value],Store([],64,128))
    else if id == 9 then state == Running(16,[value],Store([],64,128))
    else if id == 10 then state == Running(17,[],Store([],64,128))
    else if id == 11 then state == Running(19,[4],Store([],64,128))
    else if id == 12 then state == Running(20,[4,size],Store([],64,128))
    else if id == 13 then state == Running(21,[1],Store([],64,128))
    else if id == 14 then state == Running(24,[1,63],Store([],64,128))
    else if id == 15 then state == Running(63,[],Store([],64,128))
    else if id == 16 then state == Running(64,[],Store([],64,128))
    else if id == 17 then state == Running(65,[0],Store([],64,128))
    else if id == 18 then state == Running(66,[0,0],Store([],64,128))
    else false
  }
  lemma Advance0(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(0,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(1,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(0,[],[]);
    assert Fetch(code,0) == Op(96,2,128);
  }
  lemma Advance1(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(1,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(2,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(2,[128],[]);
    assert Fetch(code,2) == Op(96,4,64);
  }
  lemma Advance2(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(2,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(3,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(4,[128,64],[]);
    assert Fetch(code,4) == Op(82,5,0);
  }
  lemma Advance3(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(3,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(4,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(5,[],Store([],64,128));
    assert Fetch(code,5) == Op(52,6,0);
  }
  lemma Advance4(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(4,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(5,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(6,[value],Store([],64,128));
    assert Fetch(code,6) == Op(128,7,0);
  }
  lemma Advance5(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(5,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(6,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(7,[value,value],Store([],64,128));
    assert Fetch(code,7) == Op(21,8,0);
  }
  lemma Advance6(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(6,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(7,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(8,[value,1],Store([],64,128));
    assert Fetch(code,8) == Op(97,11,15);
  }
  lemma Advance7(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(7,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(8,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(11,[value,1,15],Store([],64,128));
    assert Fetch(code,11) == Op(87,12,0);
  }
  lemma Advance8(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(8,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(9,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(15,[value],Store([],64,128));
    assert Fetch(code,15) == Op(91,16,0);
  }
  lemma Advance9(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(9,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(10,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(16,[value],Store([],64,128));
    assert Fetch(code,16) == Op(80,17,0);
  }
  lemma Advance10(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(10,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(11,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(17,[],Store([],64,128));
    assert Fetch(code,17) == Op(96,19,4);
  }
  lemma Advance11(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(11,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(12,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(19,[4],Store([],64,128));
    assert Fetch(code,19) == Op(54,20,0);
  }
  lemma Advance12(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(12,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(13,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(20,[4,size],Store([],64,128));
    assert Fetch(code,20) == Op(16,21,0);
  }
  lemma Advance13(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(13,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(14,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(21,[1],Store([],64,128));
    assert Fetch(code,21) == Op(97,24,63);
  }
  lemma Advance14(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(14,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(15,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(24,[1,63],Store([],64,128));
    assert Fetch(code,24) == Op(87,25,0);
  }
  lemma Advance15(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(15,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(16,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(63,[],Store([],64,128));
    assert Fetch(code,63) == Op(91,64,0);
  }
  lemma Advance16(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(16,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(17,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(64,[],Store([],64,128));
    assert Fetch(code,64) == Op(95,65,0);
  }
  lemma Advance17(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(17,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); Good(18,next,value,size)
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(65,[0],Store([],64,128));
    assert Fetch(code,65) == Op(95,66,0);
  }
  lemma Advance18(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good(18,state,value,size)
    ensures state.Running? && |state.stack| <= 3 && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); next == Reverted([])
  {
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running(66,[0,0],Store([],64,128));
    assert Fetch(code,66) == Op(253,67,0);
  }
  lemma Start(value: Word, size: Word)
    ensures Good(0,Running(0,[],[]),value,size)
  { reveal Good(); }
  ghost method Run(code: seq<Byte>, value: Word, size: Word, word: Word) returns (state: State)
    requires Matches(code) && Admitted(value,size)
    ensures state == Reverted([])
  {
    Start(value,size);
    state := Running(0,[],[]);
    Advance0(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance1(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance2(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance3(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance4(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance5(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance6(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance7(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance8(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance9(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance10(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance11(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance12(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance13(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance14(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance15(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance16(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance17(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
    Advance18(code,state,value,size,word);
    state := Step(code,Destinations(),state,value,size,word);
  }
}
