#!/usr/bin/env python3
"""Generate physical-memory certificates for nonpayable/short raw entry rejection."""
import argparse,hashlib,json
from pathlib import Path
if not __debug__:raise RuntimeError('Run without Python -O')
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
def generate(out,runtime=None,only=None):
    frozen=json.loads((ROOT/'formal/bytecode/dispatch/inventory.json').read_text());out.mkdir(parents=True,exist_ok=True)
    for contract in ['Assertions','Expressions','Collections']:
        if only and contract != only:continue
        code=runtime.read_bytes() if runtime else bytes.fromhex(json.loads((ROOT/'artifacts/contracts'/f'{contract}.sol'/f'{contract}.json').read_text())['deployedBytecode'][2:])
        if not runtime:assert hashlib.sha256(code).hexdigest()==frozen[contract]['runtimeSha256']
        instructions={};p=0
        while p<len(code):
            op=code[p];w=op-95 if 96<=op<=127 else 0;instructions[p]=(op,p+1+w,int.from_bytes(code[p+1:p+1+w].ljust(w,b'\0'),'big'));p+=1+w
        destinations={p for p,(op,_,_) in instructions.items() if op==91}
        for kind in ['Nonzero','Short']:
            name=contract+kind;pc=0;s=[];expr=[];mem='[]';states=[];required={};targets=set();seen=set()
            while True:
                assert pc not in seen,'Unexpected prefix loop';seen.add(pc);op,nxt,imm=instructions[pc]
                for i in range(pc,nxt):required[i]=code[i]
                n={'id':len(states),'pc':pc,'stack':expr.copy(),'memory':mem,'op':op,'next':nxt,'immediate':imm};states.append(n)
                def pop():return s.pop(),expr.pop()
                def push(v,e=None):s.append(v);expr.append(str(v) if e is None else e)
                if op in [0x5f,0x60,0x61]:push(imm)
                elif op==0x34:push(1 if kind=='Nonzero' else 0,'value')
                elif op==0x36:push(0,'size')
                elif op==0x80:push(s[-1],expr[-1])
                elif op==0x50:pop()
                elif op==0x15:push(int(pop()[0]==0))
                elif op==0x10:a,b=pop()[0],pop()[0];push(int(a<b))
                elif op==0x52:assert pop()[0]==64 and pop()[0]==128;mem='Store([],64,128)'
                elif op==0x5b:pass
                elif op==0x57:
                    dest,truth=pop()[0],pop()[0];assert dest in destinations;targets.add(dest);required[dest]=code[dest]
                    if truth:nxt=dest
                elif op in [0xfd,0xf3]:assert pop()[0]==0 and pop()[0]==0;break
                else:raise ValueError(('Unexpected reached rejection opcode',contract,kind,pc,op))
                pc=nxt
            cap=max(len(n['stack']) for n in states);pre='value != 0' if kind=='Nonzero' else 'value == 0 && size < 4'
            matches=' &&\n    '.join(f'code[{p}] == {v}' for p,v in sorted(required.items()))
            good='\n'.join('    '+('if' if n['id']==0 else 'else if')+f" id == {n['id']} then state == Running({n['pc']},[{','.join(n['stack'])}],{n['memory']})" for n in states)+'\n    else false'
            text=f'''// SPDX-License-Identifier: MIT
// Generated by generate.py from exact pinned runtime bytes.
include "../getters/Machine.dfy"
module BytecodeReject{name} {{
  import opened BytecodeGetterMachine
  opaque predicate Matches(code: seq<Byte>) {{
    |code| == {len(code)} &&
    {matches}
  }}
  predicate Admitted(value: Word, size: Word) {{ {pre} }}
  function Destinations(): set<nat> {{ {{{','.join(map(str,sorted(targets)))}}} }}
  opaque predicate Good(id: nat, state: State, value: Word, size: Word) {{
{good}
  }}
'''
            for n in states:
                i=n['id'];post='next == Reverted([])' if i==len(states)-1 else f'Good({i+1},next,value,size)'
                text+=f'''  lemma Advance{i}(code: seq<Byte>, state: State, value: Word, size: Word, word: Word)
    requires Matches(code) && Admitted(value,size) && Good({i},state,value,size)
    ensures state.Running? && |state.stack| <= {cap} && |state.memory| <= 96
    ensures var next := Step(code,Destinations(),state,value,size,word); {post}
  {{
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running({n['pc']},[{','.join(n['stack'])}],{n['memory']});
    assert Fetch(code,{n['pc']}) == Op({n['op']},{n['next']},{n['immediate']});
  }}
'''
            calls='\n'.join(f'    Advance{i}(code,state,value,size,word);\n    state := Step(code,Destinations(),state,value,size,word);' for i in range(len(states)))
            text+=f'''  lemma Start(value: Word, size: Word)
    ensures Good(0,Running(0,[],[]),value,size)
  {{ reveal Good(); }}
  ghost method Run(code: seq<Byte>, value: Word, size: Word, word: Word) returns (state: State)
    requires Matches(code) && Admitted(value,size)
    ensures state == Reverted([])
  {{
    Start(value,size);
    state := Running(0,[],[]);
{calls}
  }}
}}
'''
            (out/(name+'.generated.dfy')).write_text(text);(out/(name+'.mapping.json')).write_text(json.dumps({'contract':contract,'kind':kind,'runtimeSha256':hashlib.sha256(code).hexdigest(),'runtimeBytes':len(code),'maximumStackWords':cap,'candidateRuntime':bool(runtime),'states':states,'requiredBytes':required},indent=2)+'\n');print(name,len(states),'complete physical rejection states')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);p.add_argument('--runtime',type=Path);p.add_argument('--contract',choices=['Assertions','Expressions','Collections']);a=p.parse_args();assert not a.runtime or a.contract;generate(a.output,a.runtime,a.contract)
