#!/usr/bin/env python3
"""Extract reached fixed decoder paths; native proof checks each symbolic step."""
import argparse, hashlib, json
from pathlib import Path
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[3]
MOD=1<<256
class E:
    def __init__(self,value,text=None):self.value=value;self.text=str(value) if text is None else text
    def __repr__(self):return self.text

def generate(out):
    code=bytes.fromhex(json.loads((ROOT/'artifacts/contracts/Collections.sol/Collections.json').read_text())['deployedBytecode'][2:])
    frozen=json.loads((ROOT/'formal/bytecode/dispatch/inventory.json').read_text())['Collections']
    assert hashlib.sha256(code).hexdigest()==frozen['runtimeSha256'];assert frozen['methodIdentifiers']['packArray(string,bytes[])']=='9c780aab'
    ins={};pc=0
    while pc<len(code):
        op=code[pc];w=op-95 if 96<=op<=127 else 0
        ins[pc]=(op,pc+1+w,int.from_bytes(code[pc+1:pc+1+w].ljust(w,b'\0'),'big'));pc+=1+w
    destinations={p for p,(op,_,_) in ins.items() if op==0x5b}
    s=[E(0x9c780aab)];pc=827;states=[];required={};targets=set();seen=set()
    def push(e):s.append(e)
    def pop():return s.pop()
    def arith(a,b,op):
        value={'+':lambda:(a.value+b.value)%MOD,'-':lambda:(a.value-b.value)%MOD}[op]()
        if a.text.isdecimal() and b.text.isdecimal():return E(value)
        pair={a.text,b.text}
        for lane in ['A','B']:
            if op=='+' and pair=={'4','Head'+lane+'(data)'}:return E(value,'HeadPosition'+lane+'(data)')
            if op=='+' and pair=={'32','HeadPosition'+lane+'(data)'}:return E(value,'Offset'+lane+'(data)')
        text=f'(({a.text} as nat)+({b.text} as nat))%G.Modulus()' if op=='+' else f'(({a.text} as nat)+G.Modulus()-({b.text} as nat))%G.Modulus()'
        return E(value,text)
    while pc!=5682:
        key=(pc,tuple(e.text for e in s));assert key not in seen;seen.add(key);assert len(states)<500
        op,nxt,imm=ins[pc]
        for p in range(pc,nxt):required[p]=code[p]
        states.append({'id':len(states),'pc':pc,'stack':[e.text for e in s],'op':op,'next':nxt,'immediate':imm})
        if op==0x5f or 0x60<=op<=0x7f:push(E(imm))
        elif op==0x5b:pass
        elif op==0x36:push(E(4096,'|data|'))
        elif 0x80<=op<=0x8f:push(s[-(op-0x7f)])
        elif 0x90<=op<=0x9f:k=op-0x8f;s[-1],s[-1-k]=s[-1-k],s[-1]
        elif op==0x50:pop()
        elif op==0x01:a,b=pop(),pop();push(arith(a,b,'+'))
        elif op==0x03:a,b=pop(),pop();push(arith(a,b,'-'))
        elif op==0x1b:
            a,b=pop(),pop()
            if a.value==5 and b.text=='LengthB(data)':push(E((b.value<<a.value)%MOD,'ArrayBytes(data)'))
            else:
                assert a.text.isdecimal() and b.text.isdecimal();push(E((b.value<<a.value)%MOD))
        elif op==0x15:push(E(int(pop().value==0)))
        elif op in [0x10,0x11,0x12]:
            a,b=pop(),pop();signed=lambda x:x if x<MOD//2 else x-MOD
            truth=a.value<b.value if op==0x10 else a.value>b.value if op==0x11 else signed(a.value)<signed(b.value)
            push(E(int(truth)))
        elif op==0x35:
            a=pop()
            if a.text=='HeadPositionA(data)':push(E(32,'LengthA(data)'))
            elif a.text=='HeadPositionB(data)':push(E(32,'LengthB(data)'))
            elif a.value==4:push(E(64,'HeadA(data)'))
            elif a.value==36:push(E(128,'HeadB(data)'))
            else:raise ValueError(('unexpected calldata offset',pc,a))
        elif op==0x56:
            dest=pop();assert dest.text.isdecimal() and dest.value in destinations;targets.add(dest.value);required[dest.value]=code[dest.value];nxt=dest.value
        elif op==0x57:
            dest,truth=pop(),pop();assert dest.text.isdecimal() and dest.value in destinations;targets.add(dest.value);required[dest.value]=code[dest.value]
            if truth.value:nxt=dest.value
        else:raise ValueError(('unsupported reached opcode',pc,op))
        pc=nxt
    final=[e.text for e in s]
    assert final==['2625112747','518','OffsetA(data)','LengthA(data)','OffsetB(data)','LengthB(data)'],final
    matches=' &&\n    '.join(f'code[{p}] == {v}' for p,v in sorted(required.items()))
    good='\n'.join('    '+('if' if n['id']==0 else 'else if')+f" id == {n['id']} then state == Running({n['pc']},[{','.join(n['stack'])}],mem)" for n in states)+'\n    else false'
    text=f'''// SPDX-License-Identifier: MIT
// Generated by generate-decoder.py from exact pinned Collections runtime instructions.
include "../../scans/Execution.dfy"
include "../../scans/DecoderScalar.dfy"
include "../../word-apply/array-stride/Stride.dfy"
module BytecodeCollectionsPackDecoder {{
  import opened BytecodeScanMachine
  import G = BytecodeGetterMachine
  import AS = BytecodeApplyArrayStride
  import DS = BytecodeScanDecoderScalar
  import F = BytecodeScanFetch
  import E = BytecodeScanExecution
  function HeadA(data: seq<Byte>): Word {{ DataWord(data,4) }}
  function HeadB(data: seq<Byte>): Word {{ DataWord(data,36) }}
  function HeadPositionA(data: seq<Byte>): Word {{ ((HeadA(data) as nat)+4)%G.Modulus() }}
  function HeadPositionB(data: seq<Byte>): Word {{ ((HeadB(data) as nat)+4)%G.Modulus() }}
  function LengthA(data: seq<Byte>): Word {{ DataWord(data,HeadPositionA(data)) }}
  function LengthB(data: seq<Byte>): Word {{ DataWord(data,HeadPositionB(data)) }}
  function OffsetA(data: seq<Byte>): Word {{ ((HeadA(data) as nat)+36)%G.Modulus() }}
  function OffsetB(data: seq<Byte>): Word {{ ((HeadB(data) as nat)+36)%G.Modulus() }}
  function ArrayBytes(data: seq<Byte>): Word {{ ((LengthB(data) as nat)*32)%G.Modulus() }}
  predicate Admitted(data: seq<Byte>) {{
    68 <= |data| < 0x10000000000000000 &&
    HeadA(data) < 0x10000000000000000 && HeadB(data) < 0x10000000000000000 &&
    (HeadA(data) as nat)+36+(LengthA(data) as nat) <= |data| &&
    LengthB(data) < 0x10000000000000000 &&
    (HeadB(data) as nat)+36+32*(LengthB(data) as nat) <= |data|
  }}
  opaque predicate Matches(code: seq<Byte>) {{
    |code| == {len(code)} &&
    {matches}
  }}
  function Destinations(): set<nat> {{ {{{','.join(map(str,sorted(targets)))}}} }}
  opaque predicate Good(id: nat, state: State, data: seq<Byte>, mem: seq<Byte>) {{
    Admitted(data) && (
{good})
  }}
'''
    cap=max(len(n['stack']) for n in states)
    for n in states:
        i=n['id'];post=f'next == Running(5682,[2625112747,518,OffsetA(data),LengthA(data),OffsetB(data),LengthB(data)],mem)' if i==len(states)-1 else f'Good({i+1},next,data,mem)'
        fetch=f"    F.Push{n['op']-95}(code,{n['pc']});\n" if n['op'] in [96,97] else ''
        if n['op']==0x1b:
            if n['stack'][-2:]==['LengthB(data)','5']:
                fetch+='    AS.Scalar(LengthB(data));\n    assert ArrayBytes(data) == 32*(LengthB(data) as nat);\n'
            else:fetch+='    DS.DecoderLimit();\n'
        text+=f'''  lemma Advance{i}(code: seq<Byte>, state: State, data: seq<Byte>, mem: seq<Byte>, value: Word)
    requires Matches(code) && Good({i},state,data,mem)
    ensures state.Running? && |state.stack| <= {cap}
    ensures Step(code,Destinations(),state,value,data).Running?
    ensures var next := Step(code,Destinations(),state,value,data); {post}
  {{
    reveal Matches(); reveal Good(); reveal Step();
    assert state == Running({n['pc']},[{','.join(n['stack'])}],mem);
{fetch}    assert Fetch(code,{n['pc']}) == Op({n['op']},{n['next']},{n['immediate']});
  }}
'''
    calls='\n'.join(f'    Advance{i}(code,state,data,mem,value);\n    var next{i} := Step(code,Destinations(),state,value,data);\n    E.Extend(code,Destinations(),value,data,trace,next{i});\n    trace := trace+[next{i}];\n    assert trace[0] == Running(827,[2625112747],mem);\n    state := next{i};' for i in range(len(states)))
    text+=f'''  lemma Start(data: seq<Byte>, mem: seq<Byte>)
    requires Admitted(data)
    ensures Good(0,Running(827,[2625112747],mem),data,mem)
  {{ reveal Good(); }}
  lemma Bounds(data: seq<Byte>)
    requires Admitted(data)
    ensures (OffsetA(data) as nat)+(LengthA(data) as nat) <= |data|
    ensures (OffsetB(data) as nat)+32*(LengthB(data) as nat) <= |data|
  {{
    assert (OffsetA(data) as nat) == (HeadA(data) as nat)+36;
    assert (OffsetB(data) as nat) == (HeadB(data) as nat)+36;
  }}
  ghost method Run(code: seq<Byte>, data: seq<Byte>, mem: seq<Byte>, value: Word) returns (state: State, trace: seq<State>)
    requires Matches(code) && Admitted(data)
    ensures state == Running(5682,[2625112747,518,OffsetA(data),LengthA(data),OffsetB(data),LengthB(data)],mem)
    ensures (OffsetA(data) as nat)+(LengthA(data) as nat) <= |data|
    ensures (OffsetB(data) as nat)+32*(LengthB(data) as nat) <= |data|
    ensures E.Trace(code,Destinations(),value,data,trace)
    ensures |trace| == {len(states)+1} && trace[0] == Running(827,[2625112747],mem) && trace[|trace|-1] == state
  {{
    Start(data,mem);
    state := Running(827,[2625112747],mem);
    trace := [state];
{calls}
    Bounds(data);
  }}
}}
'''
    out.mkdir(parents=True,exist_ok=True)
    (out/'Decoder.generated.dfy').write_text(text)
    (out/'Decoder.mapping.json').write_text(json.dumps({'runtimeSha256':hashlib.sha256(code).hexdigest(),'states':states,'requiredBytes':required,'destinations':sorted(targets),'maximumStackWords':cap,'finalStack':final,'scope':'development accepted fitting string/bytes-array head decoder, not element/body evidence'},indent=2)+'\n')
    print('Decoder',len(states),'reached instruction states',cap,'peak stack words')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();generate(a.output)
    import subprocess,sys
    subprocess.run([sys.executable,'-B',HERE/'format-generated.py','--output',a.output,'--include-root',HERE],check=True)
