#!/usr/bin/env python3
"""Exact CallbackFailed terminal control plus all-admitted healthy packet bridge.

This is diagnostic evidence only, separate from the unchanged full208-body graph.
The entire healthy bridge retains the original Admitted+Good20 domain, actual
pre-step stack/memory and exact original H.Packet bytes. No assumed call result.
"""
import argparse,json
from pathlib import Path
CONTROL = '// Exact terminal oracle over the complete actual pre-step frame.\ninclude "MACHINE"\nmodule FoldCallbackTerminalWitness {\n  import opened BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  predicate Frame(state: State,packet: seq<Byte>) {\n    state.Running? && state.pc == 1122 && 2 <= |state.stack| <= 1024 &&\n    var size: nat := state.stack[|state.stack|-2];\n    var off: nat := state.stack[|state.stack|-1];\n    off+size <= |state.memory| && state.memory[off..off+size] == packet\n  }\n  lemma Terminal(code: seq<Byte>,destinations: set<nat>,state: State,packet: seq<Byte>,value: Word,data: seq<Byte>)\n    requires 1122 < |code| && code[1122] == 253 && Frame(state,packet)\n    ensures var next := Step(code,destinations,state,value,data); next == Reverted(packet)\n  {\n    hide G.Grow();\n    var size: nat := state.stack[|state.stack|-2];\n    var off: nat := state.stack[|state.stack|-1];\n    assert Fetch(code,1122) == Op(253,1123,0);\n    assert G.Grow(state.memory,off+size) == state.memory by { reveal G.Grow(); }\n    reveal Step();\n  }\n}\n'
BRIDGE = 'include "HealthyTerminal.dfy"\ninclude "AFTER"\nmodule FoldCallbackTerminalBridge {\n  import opened BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  import A = BytecodeFoldCallbackFailedAfter\n  import T = FoldCallbackTerminalWitness\n  import M = BytecodeApplyCallbackFailedControlMemory\n  import H = BytecodeApplyCallbackFailedMemory\n  import CL = BytecodeFoldCallbackLengthScalar\n  lemma Bridge(code: seq<Byte>,state: State,data: seq<Byte>,mem: seq<Byte>,prefix: seq<Word>,domain: nat,target: Word,ptr: Word,index: Word,gasBefore: Word,receipt: Word,free: Word,payload: seq<Byte>,reason: seq<Byte>,value: Word)\n    requires A.Matches(code) && A.Admitted(data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value) && A.Good(20,state,data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value)\n    ensures 1122 < |code| && code[1122] == 253 && T.Frame(state,H.Packet(CL.Operation(domain),index,target,payload,reason))\n  {\n    hide G.Grow();hide M.Heap();hide H.Packet();hide H.Head();hide H.First();hide H.Offset();hide H.Final();hide DataWord();hide ShiftRight();\n    A.Admission(data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value);\n    M.Info(mem,ptr,receipt,free,CL.Operation(domain),index,target,payload,reason,9);\n    reveal A.Matches();reveal A.Good();\n    assert state == Running(1122,prefix+[16553,target,ptr,index,0,gasBefore,0,receipt,Round32(|payload|)+Round32(|reason|)+260,free],M.Heap(mem,ptr,receipt,free,CL.Operation(domain),index,target,payload,reason,9));\n    assert H.End(free,payload,reason) == free+Round32(|payload|)+Round32(|reason|)+260;\n    assert G.Grow(state.memory,H.End(free,payload,reason)) == state.memory by { reveal G.Grow(); }\n    A.Advance20(code,state,data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value);\n    reveal Step();\n    assert Step(code,A.Destinations(),state,value,data) == Reverted(state.memory[free..H.End(free,payload,reason)]);\n  }\n}\n'
def files(root,runtime):
 root=Path(root).resolve();code=bytes.fromhex(json.loads((root/'artifacts/contracts/Collections.sol/Collections.json').read_text())['deployedBytecode'][2:]);changed=Path(runtime).read_bytes()
 assert code[1122]==253 and len(code)==len(changed) and [(i,a,b)for i,(a,b)in enumerate(zip(code,changed))if a!=b]==[(1122,253,243)],'Callback candidate opcode/runtime drift'
 healthy=CONTROL.replace('MACHINE',str(root/'formal/bytecode/scans/Machine.dfy'))
 return {'HealthyTerminal.dfy':healthy,'ChangedTerminal.dfy':healthy.replace('code[1122] == 253','code[1122] == 243').replace('Op(253,1123,0)','Op(243,1123,0)'), 'HealthyBridge.dfy':BRIDGE.replace('AFTER',str(root/'formal/bytecode/word-fold/callback-failed-repair-v2/After.generated.dfy'))}
def main():
 parser=argparse.ArgumentParser();parser.add_argument('--root',type=Path,required=True);parser.add_argument('--runtime',type=Path,required=True);parser.add_argument('--output',type=Path,required=True);a=parser.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 for name,body in files(a.root,a.runtime).items():(a.output/name).write_text(body)
 print('Generated exact terminal witness and all-admitted packet bridge')
if __name__=='__main__':main()
