#!/usr/bin/env python3
"""Bind every Assertions ABI error signature and selector to fresh solc output."""
import argparse,hashlib,json,subprocess
from pathlib import Path
if not __debug__: raise RuntimeError('Run without Python -O')
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
def walk(v):
    if isinstance(v,dict):
        yield v
        for x in v.values():yield from walk(x)
    elif isinstance(v,list):
        for x in v:yield from walk(x)
def main():
    p=argparse.ArgumentParser();p.add_argument('--solc',type=Path,required=True);p.add_argument('--check',action='store_true');a=p.parse_args()
    assert '0.8.36+commit.8a079791' in subprocess.check_output([str(a.solc),'--version'],text=True)
    names=['contracts/Assertions.sol','contracts/lib/AbiCodec.sol','contracts/lib/ERC8211.sol']
    texts={n:(ROOT/n).read_text() for n in names}
    req={'language':'Solidity','sources':{n:{'content':v} for n,v in texts.items()},'settings':{'outputSelection':{'*':{'':['ast'],'*':['abi']}}}}
    proc=subprocess.run([str(a.solc),'--standard-json'],input=json.dumps(req),text=True,capture_output=True,check=True);out=json.loads(proc.stdout)
    assert not any(e['severity']=='error' for e in out.get('errors',[]))
    errors={e['name']:e for e in out['contracts'][names[0]]['Assertions']['abi'] if e['type']=='error'}
    expected=json.loads((HERE/'errors.json').read_text())
    assert {n:[x['type'] for x in e['inputs']] for n,e in errors.items()}==expected,'Error ABI inventory drift'
    selectors={n['name']:n['errorSelector'] for n in walk(out['sources']) if n.get('nodeType')=='ErrorDefinition'}
    assert set(selectors)==set(expected)
    enums={n['name']:[v['name'] for v in n['members']] for n in walk(out['sources']) if n.get('nodeType')=='EnumDefinition'}
    assert enums['InputParamFetcherType']==['RAW_BYTES','STATIC_CALL','BALANCE']
    assert enums['ConstraintType']==['EQ','GTE','LTE','IN','GTE_SIGNED','LTE_SIGNED','OR','SKIP','IN_SIGNED']
    tags={'uint256':'Unsigned','int256':'Signed','uint8':'Enum','address':'Address','bytes4':'Four','bytes32':'Word','bytes':'Blob','string':'Text'}
    code='// SPDX-License-Identifier: MIT\n// Generated by generate.py from fresh solc AST errorSelector and ABI types.\ninclude "../public-boundary/Connection.dfy"\n\nmodule CoreSerializationSignatures {\n  import opened AbiFrames\n  datatype Tag = Unsigned | Signed | Enum | Address | Four | Word | Blob | Text\n  datatype Error = '+ ' | '.join(sorted(errors))+' | Panic\n\n'
    code+='  function Selector(e: Error): seq<Byte>\n    ensures |Selector(e)| == 4\n  {\n    match e\n'
    for n in sorted(errors):code+='    case '+n+' => ['+','.join('0x'+selectors[n][i:i+2] for i in range(0,8,2))+']\n'
    code+='    case Panic => [0x4e,0x48,0x7b,0x71]\n  }\n  function Types(e: Error): seq<Tag> {\n    match e\n'
    for n in sorted(errors):code+='    case '+n+' => ['+','.join(tags[x] for x in expected[n])+']\n'
    code+='    case Panic => [Unsigned]\n  }\n}\n'
    dest=HERE/'Signatures.generated.dfy'
    if a.check: assert dest.read_text()==code,'Generated signature drift'
    else:dest.write_text(code)
    print(json.dumps({'status':'passed','errors':expected,'selectors':selectors,'enums':enums,'panic':'Solidity Panic(uint256) ABI rule, selector 4e487b71','sourceSha256':{n:hashlib.sha256(s.encode()).hexdigest() for n,s in texts.items()}},indent=2))
if __name__=='__main__':main()
