// SPDX-License-Identifier: MIT
// Generated by generate.py from fresh solc AST errorSelector and ABI types.
include "../public-boundary/Connection.dfy"

module CoreSerializationSignatures {
  import opened AbiFrames
  datatype Tag = Unsigned | Signed | Enum | Address | Four | Word | Blob | Text
  datatype Error = BalanceCannotBeTarget | CallFailed | ComponentCountMismatch | ConstraintFailed | DidNotRevert | DuplicateTargetParam | ElementIndexOutOfBounds | EmptyCallChain | InvalidAddressWord | InvalidBalanceData | InvalidCallbackResult | InvalidComponentEnvelope | InvalidComponentLength | InvalidComponentValue | InvalidConstraintData | InvalidConstraintRange | InvalidNavigation | InvalidOrConstraint | InvalidTypeDescriptor | InvalidValue | OutputParamsNotSupported | ReturnDataOutOfBounds | RevertProbeConstrained | RevertProbeNotACall | SubcallOutOfGas | UnexpectedRevertData | ValueParamNotSupported | Panic

  function Selector(e: Error): seq<Byte>
    ensures |Selector(e)| == 4
  {
    match e
    case BalanceCannotBeTarget => [0xe3,0xa1,0x63,0x58]
    case CallFailed => [0x6c,0x54,0x4f,0x33]
    case ComponentCountMismatch => [0x1e,0xc6,0xa9,0x56]
    case ConstraintFailed => [0xde,0xb9,0xf2,0xaf]
    case DidNotRevert => [0x82,0x60,0xeb,0xb4]
    case DuplicateTargetParam => [0xfc,0x53,0x7d,0xf8]
    case ElementIndexOutOfBounds => [0x10,0x01,0x01,0x6e]
    case EmptyCallChain => [0x39,0x55,0xaf,0xaa]
    case InvalidAddressWord => [0x57,0xbf,0x94,0x4b]
    case InvalidBalanceData => [0x66,0x08,0x8c,0x09]
    case InvalidCallbackResult => [0x24,0x44,0x8a,0x11]
    case InvalidComponentEnvelope => [0xdc,0x5d,0x12,0x62]
    case InvalidComponentLength => [0x30,0x62,0x0a,0x1b]
    case InvalidComponentValue => [0xdf,0x06,0xc5,0x1e]
    case InvalidConstraintData => [0xe7,0x0c,0xe7,0x66]
    case InvalidConstraintRange => [0x29,0x5a,0x41,0xc5]
    case InvalidNavigation => [0x65,0x62,0xa2,0x0b]
    case InvalidOrConstraint => [0xfe,0x6e,0xec,0xec]
    case InvalidTypeDescriptor => [0x9a,0x67,0xd1,0x26]
    case InvalidValue => [0x60,0x72,0x74,0x2c]
    case OutputParamsNotSupported => [0x43,0x09,0xf5,0xfc]
    case ReturnDataOutOfBounds => [0xd5,0xcb,0x84,0x36]
    case RevertProbeConstrained => [0x9f,0xb7,0xb5,0xf9]
    case RevertProbeNotACall => [0xf0,0x34,0x7a,0xc1]
    case SubcallOutOfGas => [0xd2,0x71,0x06,0x0e]
    case UnexpectedRevertData => [0xaa,0xc5,0x34,0x3e]
    case ValueParamNotSupported => [0xb0,0xc7,0x2c,0x1d]
    case Panic => [0x4e,0x48,0x7b,0x71]
  }
  function Types(e: Error): seq<Tag> {
    match e
    case BalanceCannotBeTarget => [Unsigned,Unsigned]
    case CallFailed => [Address,Blob]
    case ComponentCountMismatch => [Unsigned,Unsigned]
    case ConstraintFailed => [Text,Unsigned,Unsigned,Unsigned,Enum,Word,Blob]
    case DidNotRevert => [Address,Blob]
    case DuplicateTargetParam => [Unsigned]
    case ElementIndexOutOfBounds => [Signed,Unsigned]
    case EmptyCallChain => []
    case InvalidAddressWord => [Unsigned,Word]
    case InvalidBalanceData => [Unsigned,Unsigned,Unsigned]
    case InvalidCallbackResult => [Four,Unsigned,Unsigned,Address]
    case InvalidComponentEnvelope => [Unsigned,Unsigned,Word]
    case InvalidComponentLength => [Unsigned,Unsigned,Unsigned]
    case InvalidComponentValue => [Unsigned,Unsigned]
    case InvalidConstraintData => [Unsigned,Unsigned,Unsigned,Unsigned]
    case InvalidConstraintRange => [Unsigned,Unsigned,Unsigned]
    case InvalidNavigation => [Unsigned]
    case InvalidOrConstraint => [Unsigned,Unsigned,Unsigned]
    case InvalidTypeDescriptor => [Unsigned]
    case InvalidValue => [Unsigned]
    case OutputParamsNotSupported => [Unsigned]
    case ReturnDataOutOfBounds => [Signed,Unsigned]
    case RevertProbeConstrained => [Unsigned]
    case RevertProbeNotACall => [Enum]
    case SubcallOutOfGas => []
    case UnexpectedRevertData => [Four,Four]
    case ValueParamNotSupported => [Unsigned,Unsigned]
    case Panic => [Unsigned]
  }
}
