// Full public receipts plus every inlined bytes-encoder PC and its independent byte image.
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {network} from 'hardhat';
import {encodeFunctionData,encodeAbiParameters} from 'viem';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const options={};for(let i=2;i<process.argv.length;i+=2){if(!['--output','--root','--runtime','--case'].includes(process.argv[i])||!process.argv[i+1])throw Error('Bad args');options[process.argv[i]]=process.argv[i+1];}
const root=resolve(options['--root']??'.'),out=resolve(options['--output']),here=dirname(fileURLToPath(import.meta.url));mkdirSync(out,{recursive:true});
const artifact=JSON.parse(readFileSync(resolve(root,'artifacts/contracts/Assertions.sol/Assertions.json'))),runtime=options['--runtime']?'0x'+readFileSync(options['--runtime']).toString('hex'):artifact.deployedBytecode,digest=createHash('sha256').update(Buffer.from(runtime.slice(2),'hex')).digest('hex'),raw=bytes=>({paramType:2,fetcherType:0,paramData:bytes,constraints:[]}),fixtures=[];
for(const n of [0,1,31,32,33,257])fixtures.push({name:'bytes-'+n,values:['0x'+'a7'.repeat(n)]});
for(const n of [0,3,17])fixtures.push({name:'array-'+n,values:Array.from({length:n},(_,i)=>'0x'+(i%256).toString(16).padStart(2,'0').repeat([0,1,33,65][i%4]))});
const bytesPCs=JSON.parse(readFileSync(resolve(here,'Bytes.mapping.json'))).states.map(s=>s.pc),startPCs=JSON.parse(readFileSync(resolve(here,'Start.mapping.json'))).states.map(s=>s.pc),headPCs=JSON.parse(readFileSync(resolve(here,'Head.mapping.json'))).states.map(s=>s.pc),tailPCs=JSON.parse(readFileSync(resolve(here,'Tail.mapping.json'))).states.map(s=>s.pc),donePCs=JSON.parse(readFileSync(resolve(here,'Done.mapping.json'))).states.map(s=>s.pc);
const connection=await network.connect('hardhatMainnet'),provider=connection.provider,accounts=await provider.request({method:'eth_accounts'}),address='0x0000000000000000000000000000000000005820';await provider.request({method:'hardhat_setCode',params:[address,runtime]});const results=[];
for(const f of fixtures){if(options['--case']&&f.name!==options['--case'])continue;const data=encodeFunctionData({abi:artifact.abi,functionName:'gather',args:[f.values.map(raw)]}),expected=encodeAbiParameters([{type:'bytes[]'}],[f.values]).slice(2),trace=await provider.request({method:'debug_traceCall',params:[{from:accounts[0],to:address,gas:'0x989680',data,value:'0x0'},'latest',{enableMemory:true,disableStorage:true,disableStack:false}]}),logs=trace.structLogs.filter(x=>x.depth===1),actual=trace.returnValue.replace(/^0x/,''),receiptPassed=!trace.failed&&actual===expected,at=logs.findIndex(x=>x.pc===17316),serializerPCs=[...startPCs,...f.values.flatMap(()=>[...headPCs,...bytesPCs,...tailPCs]),...donePCs],arrayPathPassed=at>=0&&JSON.stringify(logs.slice(at,at+serializerPCs.length).map(x=>x.pc))===JSON.stringify(serializerPCs),encoders=[];
 for(let j=0;j<logs.length;j++){if(logs[j].pc!==17270)continue;const index=encoders.length,bytes=f.values[index],end=logs[j+bytesPCs.length],dst=Number(BigInt('0x'+logs[j].stack.at(-2).replace(/^0x/,''))),length=(bytes.length-2)/2,expectedEnd=dst+32+Math.ceil(length/32)*32,actualEnd=Number(BigInt('0x'+end.stack.at(-1).replace(/^0x/,''))),memory=end.memory.map(x=>x.replace(/^0x/,'')).join(''),expectedImage=BigInt(length).toString(16).padStart(64,'0')+bytes.slice(2).padEnd(Math.ceil(length/32)*64,'0'),pathPassed=JSON.stringify(logs.slice(j,j+bytesPCs.length).map(x=>x.pc))===JSON.stringify(bytesPCs),imagePassed=memory.slice(dst*2,expectedEnd*2)===expectedImage,endPassed=actualEnd===expectedEnd;encoders.push({index,length,dst,expectedEnd,actualEnd,pathPassed,imagePassed,endPassed,passed:pathPassed&&imagePassed&&endPassed});}
 const passed=receiptPassed&&arrayPathPassed&&encoders.length===f.values.length&&encoders.every(x=>x.passed);writeFileSync(resolve(out,f.name+'.json'),JSON.stringify({name:f.name,runtimeSha256:digest,data,values:f.values,expectedBytes:expected,trace,encoders},null,2)+'\n');results.push({name:f.name,receiptPassed,arrayPathPassed,actualFailed:trace.failed,expectedBytes:expected,actualBytes:actual,encoders,passed});}
await connection.close();
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),hh=fileURLToPath(import.meta.resolve('hardhat')),edr=createRequire(hh).resolve('@nomicfoundation/edr'),binding=createRequire(edr).resolve('@nomicfoundation/edr-linux-x64-gnu');
writeFileSync(resolve(out,'toolchain.json'),JSON.stringify({nodeVersion:process.version,nodeExecutable:process.execPath,nodeSha256:sha(readFileSync(process.execPath)),hardhatEntry:hh,hardhatEntrySha256:sha(readFileSync(hh)),edrEntry:edr,edrEntrySha256:sha(readFileSync(edr)),edrVersion:JSON.parse(readFileSync(resolve(dirname(edr),'package.json'))).version,nativeBinding:binding,nativeBindingSha256:sha(readFileSync(binding)),lockfileSha256:sha(readFileSync(resolve(root,'pnpm-lock.yaml')))},null,2)+'\n');
if(results.length!==(options['--case']?1:fixtures.length))throw Error('Wrong fixture inventory');
writeFileSync(resolve(out,'results.json'),JSON.stringify(results,null,2)+'\n');console.log(results.every(x=>x.passed)?'PASS':'FAIL',results.length,'complete gather receipts and arbitrary bytes encoder traces');process.exitCode=results.every(x=>x.passed)?0:1;
