#!/usr/bin/env python3
"""Retain exact unbounded PC477 -> canonical bytes[] RETURN serializer closure."""
import sys,json,re,shutil,concurrent.futures,threading,importlib.util,datetime,subprocess,csv
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[4]
def module(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
g=module('control',ROOT/'formal/bytecode/assertions-primitives-control/verify.py');getter=g.getter;common=g.common;sha=g.sha
out=Path(sys.argv[1]).resolve();out.mkdir(parents=True,exist_ok=False);closure=g.graph(HERE/'Entry.dfy');snapshot=out/'source-snapshot';fixture=ROOT/'formal/bytecode/assertions-primitives-control/gather-composition/evidence/element-native-v1/evm-traces/element-33.json';files=set(closure)|set(getter.inputs())|{f for f in HERE.iterdir() if f.is_file()}|{fixture,ROOT/'formal/bytecode/assertions-primitives-control/verify.py'};hashes={str(f.relative_to(ROOT)):sha(f) for f in sorted(files)}
for f in files:
 target=snapshot/f.relative_to(ROOT);target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(f,target)
dafny=Path('/home/sem/assertions-tools/dafny/dafny');node=Path('/home/sem/assertions-tools/node-v24.14.0-linux-x64/bin/node');solc=Path('/home/sem/assertions-tools/solc-0.8.36');tools={'dafny':dafny,'Dafny.dll':dafny.parent/'Dafny.dll','z3':dafny.parent/'z3/bin/z3-4.12.1','solc':solc,'node':node};lock=threading.Lock();manifest={'schemaVersion':1,'status':'incomplete','startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'contracts':['Assertions'],'scope':'Exact physical gather serializer suffix PC477 through standard RETURN, for arbitrary bounded count and arbitrary original byte values. Every actual array-head, offset, length, MCOPY, zero-padding, loop update and RETURN instruction is represented, and a decreasing count-index invariant composes all items without a fixture or execution cutoff. Independent returned bytes[] specification includes every item offset, length, payload and padding. Fresh dispatcher/decoder/resolver composition and whole gather/whole Assertions remain open.','publicEntries':[],'suffix':{'entryPC':477,'specification':'AssertionsGatherArrayResult.Result','theorem':'AssertionsGatherSerializerWrapper.Run','unboundedCount':True,'wholeEntry':False},'includeClosure':[str(f.relative_to(ROOT)) for f in closure],'sourceSha256':hashes,'versions':{k:subprocess.check_output([str(v),'--version'],text=True).strip() for k,v in tools.items() if k!='Dafny.dll'},'executableSha256':{k:sha(v) for k,v in tools.items()},'proofMode':'Complete per-file native verification with global assertion isolation, exact file position and module filters, every transitive declaration inventoried. The context matches accepted development/native dependency verification.','checks':[],'assumptions':['Reviewed reached instruction semantics, exact compiler identity and full-runtime instruction-boundary scan are trusted; adequate execution resources remain premises.','Reached physical byte memory satisfies independent pointer/header/source payload layout, nonoverlap, alignment and nonwrapping 64-bit allocator bounds. Caller return labels are actual scanned runtime destinations.','The suffix begins at PC477 after gather resolution; successful source bytes are already materialized in memory. This proof does not assume an ABI serializer implementation is correct.','Dafny/Boogie/Z3, solc, Node/Hardhat/EDR and evidence scripts are trusted. This is a complete serializer suffix proof, not a fresh public-entry or whole-contract claim.']}
assert manifest['versions']['dafny']==json.loads((ROOT/'formal/abi/toolchain.json').read_text())['dafnyVersion'] and '4.12.1' in manifest['versions']['z3'] and '0.8.36+commit.8a079791' in manifest['versions']['solc']
def save():
 with lock:(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
def record(name,cmd,timeout=7200):
 job=common.run(cmd,out/(name+'.log'),timeout);job.update(name=name,passed=job['exitCode']==0)
 with lock:manifest['checks'].append(job)
 save();return job
save();record('runtime-identity',[sys.executable,'-B',snapshot/'formal/bytecode/dispatch/identity.py','--contract','Assertions','--solc',solc,'--output',out/'identity'],300)
regen=out/'regeneration';shutil.copytree(snapshot,regen);source=regen/HERE.relative_to(ROOT);names=['Bytes','Start','Head','Tail','Done','Before','Return']
for script in ['generate.py','generate-array.py','generate-hooks.py']:record('generation-'+script,[sys.executable,'-B',source/script],300)
for name in names:record('generation-format-'+name,[dafny,'format',source/(name+'.generated.dfy')],300)
manifest['generationIdentical']=all((source/(name+suffix)).read_bytes()==(snapshot/HERE.relative_to(ROOT)/(name+suffix)).read_bytes() for name in names for suffix in ['.generated.dfy','.mapping.json']);save()
if not manifest['generationIdentical'] or not all(x['passed'] for x in manifest['checks']):manifest['status']='failed';save();raise SystemExit('Identity/generation failed; diagnostics retained')
def prove(f):
 name=re.search(r'^module (\w+)',f.read_text(),re.M)[1];file=snapshot/f.relative_to(ROOT);csvfile=out/('proof-'+name+'.csv');cmd=common.proof_command(dafny,file,csvfile);cmd[cmd.index('--cores')+1]='1';cmd+=['--filter-symbol',name,'--filter-position',str(file),'--progress','Symbol'];job=record('proof-'+name,cmd);common.check_proof(job,out/('proof-'+name+'.log'),csvfile,getter.inventory(f));save();print(name,len(job['nativeResults']),'passed' if job['passed'] else 'FAILED',flush=True);return job
with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:jobs=list(pool.map(prove,[f for f in closure if re.search(r'^module (\w+)',f.read_text(),re.M)]))
manifest['nativeResults']=[r for job in jobs for r in job['nativeResults']];manifest['declarationResults']=[d for job in jobs for d in job['declarations']];save()
audit=record('audit',[dafny,'audit',snapshot/HERE.relative_to(ROOT)/'Entry.dfy'],300);audit['passed'] &= 'auditor completed with 0 findings' in (out/'audit.log').read_text();record('format',[dafny,'format','--check',*[snapshot/f.relative_to(ROOT) for f in closure]],300)
concrete=record('concrete',[node,HERE/'evm-traces.mjs','--root',snapshot,'--output',out/'evm-traces'],300);rows=json.loads((out/'evm-traces/results.json').read_text());concrete['passed'] &= len(rows)==9 and all(x['passed'] for x in rows);manifest['concreteToolchain']=json.loads((out/'evm-traces/toolchain.json').read_text());save()
mutation=out/'mutations/mask-30';mutation.mkdir(parents=True);bytesFile=HERE/'Bytes.generated.dfy';candidateSource=mutation/'source-snapshot';mutClosure=g.graph(bytesFile)
for f in mutClosure:
 dest=candidateSource/f.relative_to(ROOT);dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(snapshot/f.relative_to(ROOT),dest)
file=candidateSource/bytesFile.relative_to(ROOT);text=file.read_text();assert text.count('code[17298] == 31')==1;file.write_text(text.replace('code[17298] == 31','code[17298] == 30'));csvfile=mutation/'proof.csv';cmd=common.proof_command(dafny,file,csvfile);cmd[cmd.index('--cores')+1]='1';cmd+=['--filter-symbol','AssertionsGatherBytesEncoder.Advance23.','--filter-position',str(file),'--progress','Symbol'];job=record('mutation-native-mask-30',cmd,300);text=(out/'mutation-native-mask-30.log').read_text();results=list(csv.DictReader(csvfile.open())) if csvfile.exists() else [];job['passed']=job['exitCode'] not in [0,None] and bool(results) and any(x['TestResult.Outcome']=='Failed' for x in results) and all(x['TestResult.Outcome'] in {'Passed','Failed'} for x in results) and 'postcondition could not be proved' in text and not re.search(r'timed out|inconclusive|resource limit|parse error|resolution/type error',text);job['expectedSemanticFailure']=True
baseline=next(x for x in jobs if x['name']=='proof-AssertionsGatherBytesEncoder');assert next(x for x in baseline['declarations'] if x['name']=='AssertionsGatherBytesEncoder.Advance23')['status']=='passed';runtime=bytes.fromhex(json.loads((snapshot/'artifacts/contracts/Assertions.sol/Assertions.json').read_text())['deployedBytecode'][2:]);assert runtime[17297:17299]==bytes([96,31]);mutated=bytearray(runtime);mutated[17298]=30;candidate=mutation/'runtime.bin';candidate.write_bytes(mutated);job=record('mutation-complete-receipt-mask-30',[node,HERE/'evm-traces.mjs','--root',snapshot,'--runtime',candidate,'--case','bytes-32','--output',mutation/'evm'],300);rows=json.loads((mutation/'evm/results.json').read_text());job['passed']=job['exitCode'] not in [0,None] and len(rows)==1 and not rows[0]['receiptPassed'] and not rows[0]['actualFailed'];job['expectedSemanticFailure']=True;manifest['mutation']={'runtimeByte':17298,'before':31,'after':30,'baselineDeclaration':'AssertionsGatherBytesEncoder.Advance23','nativeSourceSha256':sha(file),'runtimeSha256':sha(candidate),'semanticReceiptCase':'bytes-32'}
manifest['inputsUnchanged']=all(sha(ROOT/f)==h and sha(snapshot/f)==h for f,h in hashes.items());manifest['toolsUnchanged']=all(sha(v)==manifest['executableSha256'][k] for k,v in tools.items());ct=manifest['concreteToolchain'];manifest['concreteToolsUnchanged']=all(sha(Path(ct[k]))==ct[k+'Sha256'] for k in ['hardhatEntry','edrEntry','nativeBinding']) and sha(Path(ct['nodeExecutable']))==ct['nodeSha256'] and sha(ROOT/'pnpm-lock.yaml')==ct['lockfileSha256'];manifest['status']='passed' if manifest['inputsUnchanged'] and manifest['toolsUnchanged'] and manifest['concreteToolsUnchanged'] and manifest['generationIdentical'] and all(job['passed'] for job in manifest['checks']) else 'failed';manifest['finishedAt']=datetime.datetime.now(datetime.timezone.utc).isoformat();save();manifest['evidenceSha256']={str(f.relative_to(out)):sha(f) for f in out.rglob('*') if f.is_file() and f.name!='manifest.json' and 'source-snapshot' not in f.parts};save();print(manifest['status'],len(manifest['nativeResults']),flush=True);raise SystemExit(0 if manifest['status']=='passed' else 1)
