#!/usr/bin/env python3
"""Generate constructive big-endian byte/XOR bridges; native pending."""
import argparse,subprocess
from pathlib import Path
def generate(out):
 text='// SPDX-License-Identifier: MIT\n// Constructive byte at high end of EVM word; native pending.\ninclude "Machine.dfy"\ninclude "../casefold-inputs/Inputs.dfy"\ninclude "../../word-apply/word-conversion/Conversion.generated.dfy"\ninclude "../../word-fold/byte-representation-repair-v8/Shift.generated.dfy"\nmodule OperationsCaseFoldBinary {\n  import S = BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  import F = OperationsCaseFoldMachine\n  import I = OperationsCaseFoldInputs\n  import W = BytecodeApplyWordConversion\n  import B = BytecodeFoldByteShiftV8\n  function Top8(cell:bv8):bv8 { cell }\n  lemma Nat8(cell:bv8)\n    ensures (Top8(cell) as nat)==(cell as nat)\n  {}\n'
 for width in [16,32,64,128,256]:
  half=width//2;text+=f'  function Top{width}(cell:bv8):bv{width} {{ (Top{half}(cell) as bv{width})<<{half} }}\n  lemma Nat{width}(cell:bv8)\n    ensures (Top{width}(cell) as nat)==(cell as nat)*{1<<(width-8)}\n  {{\n    Nat{half}(cell);W.Join{width}(Top{half}(cell),0);\n    assert Top{width}(cell)==((Top{half}(cell) as bv{width})<<{half})|((0 as bv{half}) as bv{width});\n  }}\n'
 text+='  function Cell(cell:S.Byte):S.Word { Top256(cell as bv8) as nat }\n  function Mask():S.Word { Cell(255) }\n  lemma CellWord(cell:S.Byte)\n    ensures Cell(cell)==(cell as nat)*'+str(1<<248)+'\n    ensures S.ShiftLeft(cell,248)==Cell(cell)\n  {\n    W.Nat8(cell);W.Nat256(cell);Nat256(cell as bv8);\n    assert Top256(cell as bv8)==(cell as bv256)<<248;\n    reveal S.ShiftLeft();\n  }\n'
 text+='  lemma Xor(cell:S.Byte)\n    ensures F.Xor(Cell(cell),Cell(32))==Cell(((cell as bv8)^(32 as bv8)) as nat)\n  {\n    W.Nat8(cell);W.Nat8(((cell as bv8)^(32 as bv8)) as nat);\n    assert Top256(cell as bv8)^Top256(32 as bv8)==Top256((cell as bv8)^(32 as bv8));\n  }\n'
 text+='  lemma Compare(a:S.Byte,b:S.Byte)\n    ensures Cell(a)<Cell(b) <==> a<b\n    ensures Cell(a)>Cell(b) <==> a>b\n  { CellWord(a);CellWord(b); }\n  lemma Fold(lower:bool,cell:S.Byte)\n    requires I.Low(lower)<=cell<=I.High(lower)\n    ensures F.Xor(Cell(cell),Cell(32))==Cell(I.Fold(lower,cell))\n  { Xor(cell); }\n'
 text+='  lemma PowerLiteral()\n    ensures G.Pow256(31)=='+str(1<<248)+'\n  {\n'
 for n in range(1,32):text+=f'    assert G.Pow256({n})=={1<<(8*n)};\n'
 text+='  }\n  lemma ByteCell(cell:S.Byte)\n    ensures F.Byte(Cell(cell),0)==cell\n  { CellWord(cell);PowerLiteral(); }\n  lemma MaskCell(cell:S.Byte)\n    ensures G.BitAnd(Cell(cell),Mask())==Cell(cell)\n  { W.Nat256(Cell(cell));W.Nat256(Mask());assert Top256(cell as bv8)&Top256(255 as bv8)==Top256(cell as bv8); }\n  lemma First(word:S.Word) returns(cell:S.Byte)\n    ensures cell==F.Byte(word,0)\n    ensures G.BitAnd(word,Mask())==Cell(cell)\n  {\n    cell:=((word as bv256)>>248) as bv8 as nat;\n    W.Nat256(word);W.Nat8(cell);B.Top256(word as bv256);PowerLiteral();\n    assert ((word as bv256)&Top256(255 as bv8))==Top256(cell as bv8);\n  }\n}\n';r=subprocess.run(['/tmp/assertions-dafny-4.11.0/dafny/dafny','format','--stdin','--print'],input=text.replace('include "','//FORMAT_INCLUDE "'),capture_output=True,text=True);assert r.returncode==0,r.stderr;out.mkdir(parents=True,exist_ok=True);(out/'Binary.generated.dfy').write_text(r.stdout.replace('//FORMAT_INCLUDE "','include "'))
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);generate(p.parse_args().output)
