// Complete public receipts and every PC of the unbounded RAW gather class.
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {network} from 'hardhat';
import {encodeFunctionData,encodeAbiParameters} from 'viem';
const options={};for(let i=2;i<process.argv.length;i+=2){if(!['--root','--output','--runtime','--case'].includes(process.argv[i])||!process.argv[i+1])throw Error('Bad args');options[process.argv[i]]=process.argv[i+1];}
const root=resolve(options['--root']??'.'),out=resolve(options['--output']);mkdirSync(out,{recursive:true});const artifact=JSON.parse(readFileSync(resolve(root,'artifacts/contracts/Assertions.sol/Assertions.json'))),runtime=options['--runtime']?'0x'+readFileSync(options['--runtime']).toString('hex'):artifact.deployedBytecode,sha=x=>createHash('sha256').update(x).digest('hex'),digest=sha(Buffer.from(runtime.slice(2),'hex')),raw=bytes=>({paramType:2,fetcherType:0,paramData:bytes,constraints:[]}),base='formal/bytecode/assertions-primitives-control',fixtureRoot=resolve(root,base,'gather-composition/evidence/element-native-v1/evm-traces'),fixtures=[],word=x=>BigInt(x).toString(16).padStart(64,'0'),M=1n<<256n,signed=x=>x<1n<<255n?x:x-M;
for(const n of [0,1,31,32,33,257])fixtures.push({name:'bytes-'+n,values:['0x'+'a7'.repeat(n)]});
for(const n of [0,3,17])fixtures.push({name:'array-'+n,values:Array.from({length:n},(_,i)=>'0x'+i.toString(16).padStart(2,'0').repeat([0,1,33,65][i%4]))});
for(const [name,values] of [['element-negative-alias',['0xaa']],['element-tight128',['0x0000']]])fixtures.push({name,values,data:JSON.parse(readFileSync(resolve(fixtureRoot,name+'.json'))).data});
const canonical=encodeFunctionData({abi:artifact.abi,functionName:'gather',args:[['0xabab'].map(raw)]});fixtures.push({name:'relocated-196',values:['0xabab'],data:canonical.slice(0,10)+word(196)+'c7'.repeat(164)+canonical.slice(74)});fixtures.push({name:'trailing',values:['0xabab'],data:canonical+'cafe'.repeat(97)});
const pcs=(dir,name)=>JSON.parse(readFileSync(resolve(root,dir,name+'.mapping.json'))).states.map(x=>x.pc),dispatch=pcs(base+'/gather-public','Dispatch'),decoder=pcs(base+'/gather-public','Decoder'),start=pcs(base,'GatherStart'),zero=pcs(base,'GatherStartZero'),fill=pcs(base,'GatherFill'),last=pcs(base,'GatherFillLast'),exit=pcs(base,'GatherHeaderExit'),iteration=[...pcs(base,'GatherNext'),...pcs(base+'/gather-composition','ElementSuccess'),...pcs(base,'GatherParam'),...pcs('formal/bytecode/assertions-resolution/raw','Raw'),...pcs(base,'GatherValueStore')],done=pcs(base,'GatherDoneExit'),ser=base+'/gather-public/serialization',serHead=pcs(ser,'Start'),serItem=[...pcs(ser,'Head'),...pcs(ser,'Bytes'),...pcs(ser,'Tail')],serDone=pcs(ser,'Done'),before=pcs(ser,'Before'),ret=pcs(ser,'Return');
const connection=await network.connect('hardhatMainnet'),provider=connection.provider,accounts=await provider.request({method:'eth_accounts'}),address='0x0000000000000000000000000000000000005830';await provider.request({method:'hardhat_setCode',params:[address,runtime]});const results=[];
for(const f of fixtures){if(options['--case']&&f.name!==options['--case'])continue;const data=f.data??encodeFunctionData({abi:artifact.abi,functionName:'gather',args:[f.values.map(raw)]}),bytes=Buffer.from(data.slice(2),'hex'),read=off=>BigInt('0x'+Buffer.from(Array.from({length:32},(_,i)=>bytes[Number(off)+i]??0)).toString('hex')),relative=read(4),count=read(4n+relative),args=4n+relative+32n,items=[];
 for(let j=0;j<f.values.length;j++){const rel=read(args+32n*BigInt(j)),operand=(args+rel)%M,bytesRelative=read(operand+64n),constraintsRelative=read(operand+96n),length=read(operand+bytesRelative),guard=signed(rel)<signed((BigInt(bytes.length)+2n*M-args-127n)%M),payload='0x'+bytes.subarray(Number(operand+bytesRelative+32n),Number(operand+bytesRelative+32n+length)).toString('hex'),passed=guard&&operand+128n<=BigInt(bytes.length)&&operand+bytesRelative+32n+length<=BigInt(bytes.length)&&operand+constraintsRelative+32n<=BigInt(bytes.length)&&read(operand+32n)===0n&&read(operand+constraintsRelative)===0n&&payload===f.values[j];items.push({operand:operand.toString(),bytesRelative:bytesRelative.toString(),constraintsRelative:constraintsRelative.toString(),length:length.toString(),passed});}
 const expected=encodeAbiParameters([{type:'bytes[]'}],[f.values]).slice(2),trace=await provider.request({method:'debug_traceCall',params:[{from:accounts[0],to:address,gas:'0x989680',data,value:'0x0'},'latest',{enableMemory:true,disableStorage:true,disableStack:false}]}),logs=trace.structLogs.filter(x=>x.depth===1),actual=trace.returnValue.replace(/^0x/,''),receiptPassed=!trace.failed&&actual===expected,n=f.values.length,expectedPCs=[...dispatch,...decoder,...(n===0?zero:[...start,...Array.from({length:Math.max(0,n-1)},()=>fill).flat(),...last,...exit]),...Array.from({length:n},()=>iteration).flat(),...done,...before,...serHead,...Array.from({length:n},()=>serItem).flat(),...serDone,...ret],actualPCs=logs.map(x=>x.pc),pathPassed=JSON.stringify(actualPCs)===JSON.stringify(expectedPCs),firstMismatch=actualPCs.findIndex((pc,i)=>pc!==expectedPCs[i]),classPassed=count===BigInt(n)&&4n+relative+32n+count*32n<=BigInt(bytes.length)&&items.every(x=>x.passed),passed=classPassed&&receiptPassed&&pathPassed;
 writeFileSync(resolve(out,f.name+'.json'),JSON.stringify({name:f.name,runtimeSha256:digest,data,values:f.values,relative:relative.toString(),count:count.toString(),items,expectedBytes:expected,expectedPCs,trace},null,2)+'\n');results.push({name:f.name,classPassed,receiptPassed,pathPassed,actualFailed:trace.failed,expectedBytes:expected,actualBytes:actual,expectedSteps:expectedPCs.length,actualSteps:actualPCs.length,firstMismatch,passed});}
await connection.close();const hh=fileURLToPath(import.meta.resolve('hardhat')),edr=createRequire(hh).resolve('@nomicfoundation/edr'),binding=createRequire(edr).resolve('@nomicfoundation/edr-linux-x64-gnu');writeFileSync(resolve(out,'toolchain.json'),JSON.stringify({nodeVersion:process.version,nodeExecutable:process.execPath,nodeSha256:sha(readFileSync(process.execPath)),hardhatEntry:hh,hardhatEntrySha256:sha(readFileSync(hh)),edrEntry:edr,edrEntrySha256:sha(readFileSync(edr)),edrVersion:JSON.parse(readFileSync(resolve(dirname(edr),'package.json'))).version,nativeBinding:binding,nativeBindingSha256:sha(readFileSync(binding)),lockfileSha256:sha(readFileSync(resolve(root,'pnpm-lock.yaml')))},null,2)+'\n');if(results.length!==(options['--case']?1:fixtures.length))throw Error('Wrong fixture inventory');writeFileSync(resolve(out,'results.json'),JSON.stringify(results,null,2)+'\n');console.log(results.every(x=>x.passed)?'PASS':'FAIL',results.length,'complete RAW gather receipts and every physical instruction');process.exitCode=results.every(x=>x.passed)?0:1;
