#!/usr/bin/env python3
"""Bind public operation contexts to pinned compiler method identifiers."""
import argparse,gzip,hashlib,json,subprocess
from pathlib import Path
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
def generate(solc,root,out):
    if '0.8.36+commit.8a079791' not in subprocess.check_output([str(solc),'--version'],text=True):raise ValueError('Wrong compiler')
    sources={p:(root/p).read_text() for p in ['contracts/Collections.sol','contracts/lib/AbiCodec.sol']}
    request={'language':'Solidity','sources':{p:{'content':v} for p,v in sources.items()},'settings':{'evmVersion':'cancun','outputSelection':{'*':{'Collections':['evm.methodIdentifiers']}}}}
    proc=subprocess.run([str(solc),'--standard-json'],input=json.dumps(request),capture_output=True,text=True,check=True)
    result=json.loads(proc.stdout)
    if any(x['severity']=='error' for x in result.get('errors',[])):raise ValueError(result['errors'])
    identifiers=result['contracts']['contracts/Collections.sol']['Collections']['evm']['methodIdentifiers']
    entries={}
    for name in ['mapValues','filterValues','foldValues']:
        matches=[(sig,value) for sig,value in identifiers.items() if sig.startswith(name+'(')]
        if len(matches)!=1:raise ValueError('Ambiguous or missing '+name)
        entries[name]={'signature':matches[0][0],'selector':matches[0][1]}
    code='// SPDX-License-Identifier: MIT\n// Generated by generate.py from pinned solc method identifiers.\ninclude "../../abi/Frames.dfy"\nmodule CollectionsValueEntrySelectors {\n  import opened AbiFrames\n'
    for name,entry in entries.items():
        code+='  function '+name+'(): seq<Byte> { ['+','.join(str(x) for x in bytes.fromhex(entry['selector']))+'] }\n'
    code+='}\n'
    out.mkdir(parents=True,exist_ok=True)
    (out/'Selectors.generated.dfy').write_text(code)
    (out/'solc-input.json').write_text(json.dumps(request))
    (out/'solc-output.json.gz').write_bytes(gzip.compress(proc.stdout.encode(),mtime=0))
    (out/'selectors.json').write_text(json.dumps({'entries':entries,'sourceSha256':{k:hashlib.sha256(v.encode()).hexdigest() for k,v in sources.items()}},indent=2)+'\n')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--solc',type=Path,required=True);p.add_argument('--root',type=Path,default=ROOT);p.add_argument('--output',type=Path,required=True);a=p.parse_args();generate(a.solc,a.root,a.output)
