// SPDX-License-Identifier: MIT
// Generated by generate.py from pinned solc method identifiers.
include "../../abi/Frames.dfy"
module CollectionsValueEntrySelectors {
  import opened AbiFrames
  function mapValues(): seq<Byte> { [57,81,56,13] }
  function filterValues(): seq<Byte> { [59,65,229,165] }
  function foldValues(): seq<Byte> { [117,13,130,215] }
}
