// Generated by scripts/export-deploy-artifact.mjs, do not edit by hand.
export const ASSERTIONS_ABI = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paramIndex",
        "type": "uint256"
      }
    ],
    "name": "BalanceCannotBeTarget",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "CallFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "expected",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "actual",
        "type": "uint256"
      }
    ],
    "name": "ComponentCountMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "assertion",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paramIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "constraintIndex",
        "type": "uint256"
      },
      {
        "internalType": "enum ConstraintType",
        "name": "constraintType",
        "type": "uint8"
      },
      {
        "internalType": "bytes32",
        "name": "actual",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "referenceData",
        "type": "bytes"
      }
    ],
    "name": "ConstraintFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "callData",
        "type": "bytes"
      }
    ],
    "name": "DidNotRevert",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      }
    ],
    "name": "DuplicateTargetParam",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "index",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "name": "ElementIndexOutOfBounds",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyCallChain",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "word",
        "type": "bytes32"
      }
    ],
    "name": "InvalidAddressWord",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paramIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "InvalidBalanceData",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "operation",
        "type": "bytes4"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "other",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "InvalidCallbackResult",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "head",
        "type": "bytes32"
      }
    ],
    "name": "InvalidComponentEnvelope",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expectedBytes",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "actualBytes",
        "type": "uint256"
      }
    ],
    "name": "InvalidComponentLength",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidComponentValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paramIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "constraintIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "InvalidConstraintData",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "position",
        "type": "uint256"
      }
    ],
    "name": "InvalidNavigation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "position",
        "type": "uint256"
      }
    ],
    "name": "InvalidTypeDescriptor",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      }
    ],
    "name": "OutputParamsNotSupported",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "index",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "ReturnDataOutOfBounds",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "name": "RevertProbeConstrained",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "fetcherType",
        "type": "uint8"
      }
    ],
    "name": "RevertProbeNotACall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "expected",
        "type": "bytes4"
      },
      {
        "internalType": "bytes4",
        "name": "actual",
        "type": "bytes4"
      }
    ],
    "name": "UnexpectedRevertData",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paramIndex",
        "type": "uint256"
      }
    ],
    "name": "ValueParamNotSupported",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LEN",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "PAYLOAD",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes4",
            "name": "functionSig",
            "type": "bytes4"
          },
          {
            "components": [
              {
                "internalType": "enum InputParamType",
                "name": "paramType",
                "type": "uint8"
              },
              {
                "internalType": "enum InputParamFetcherType",
                "name": "fetcherType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "paramData",
                "type": "bytes"
              },
              {
                "components": [
                  {
                    "internalType": "enum ConstraintType",
                    "name": "constraintType",
                    "type": "uint8"
                  },
                  {
                    "internalType": "bytes",
                    "name": "referenceData",
                    "type": "bytes"
                  }
                ],
                "internalType": "struct Constraint[]",
                "name": "constraints",
                "type": "tuple[]"
              }
            ],
            "internalType": "struct InputParam[]",
            "name": "inputParams",
            "type": "tuple[]"
          },
          {
            "components": [
              {
                "internalType": "enum OutputParamFetcherType",
                "name": "fetcherType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "paramData",
                "type": "bytes"
              }
            ],
            "internalType": "struct OutputParam[]",
            "name": "outputParams",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct ComposableExecution[]",
        "name": "executions",
        "type": "tuple[]"
      }
    ],
    "name": "assertComposable",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes4",
            "name": "functionSig",
            "type": "bytes4"
          },
          {
            "components": [
              {
                "internalType": "enum InputParamType",
                "name": "paramType",
                "type": "uint8"
              },
              {
                "internalType": "enum InputParamFetcherType",
                "name": "fetcherType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "paramData",
                "type": "bytes"
              },
              {
                "components": [
                  {
                    "internalType": "enum ConstraintType",
                    "name": "constraintType",
                    "type": "uint8"
                  },
                  {
                    "internalType": "bytes",
                    "name": "referenceData",
                    "type": "bytes"
                  }
                ],
                "internalType": "struct Constraint[]",
                "name": "constraints",
                "type": "tuple[]"
              }
            ],
            "internalType": "struct InputParam[]",
            "name": "inputParams",
            "type": "tuple[]"
          },
          {
            "components": [
              {
                "internalType": "enum OutputParamFetcherType",
                "name": "fetcherType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "paramData",
                "type": "bytes"
              }
            ],
            "internalType": "struct OutputParam[]",
            "name": "outputParams",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct ComposableExecution[]",
        "name": "executions",
        "type": "tuple[]"
      },
      {
        "internalType": "string",
        "name": "message",
        "type": "string"
      }
    ],
    "name": "assertComposable",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "param",
        "type": "tuple"
      },
      {
        "internalType": "string",
        "name": "message",
        "type": "string"
      }
    ],
    "name": "assertParam",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "param",
        "type": "tuple"
      }
    ],
    "name": "assertParam",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "start",
        "type": "tuple"
      },
      {
        "internalType": "bytes[]",
        "name": "calls",
        "type": "bytes[]"
      }
    ],
    "name": "chain",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "c",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "then_",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "else_",
        "type": "tuple"
      }
    ],
    "name": "cond",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "a",
        "type": "tuple"
      }
    ],
    "name": "isValid",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "a",
        "type": "tuple"
      },
      {
        "internalType": "string",
        "name": "retTypes",
        "type": "string"
      },
      {
        "internalType": "int256[]",
        "name": "path",
        "type": "int256[]"
      }
    ],
    "name": "nav",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "a",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "b",
        "type": "tuple"
      }
    ],
    "name": "orElse",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "param",
        "type": "tuple"
      },
      {
        "internalType": "int256",
        "name": "wordIndex",
        "type": "int256"
      }
    ],
    "name": "pick",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "target",
        "type": "tuple"
      },
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam[]",
        "name": "args",
        "type": "tuple[]"
      }
    ],
    "name": "read",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "target",
        "type": "tuple"
      },
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "internalType": "string",
        "name": "argumentTypes",
        "type": "string"
      },
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam[]",
        "name": "args",
        "type": "tuple[]"
      }
    ],
    "name": "readArgs",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "param",
        "type": "tuple"
      }
    ],
    "name": "resolve",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum InputParamType",
            "name": "paramType",
            "type": "uint8"
          },
          {
            "internalType": "enum InputParamFetcherType",
            "name": "fetcherType",
            "type": "uint8"
          },
          {
            "internalType": "bytes",
            "name": "paramData",
            "type": "bytes"
          },
          {
            "components": [
              {
                "internalType": "enum ConstraintType",
                "name": "constraintType",
                "type": "uint8"
              },
              {
                "internalType": "bytes",
                "name": "referenceData",
                "type": "bytes"
              }
            ],
            "internalType": "struct Constraint[]",
            "name": "constraints",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct InputParam",
        "name": "a",
        "type": "tuple"
      },
      {
        "internalType": "bytes4",
        "name": "expectedSelector",
        "type": "bytes4"
      }
    ],
    "name": "revertData",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
