// Generated by scripts/export-deploy-artifact.mjs — do not edit by hand.
export const COLLECTION_OPERATORS_ABI = [
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "operation",
        "type": "bytes4"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "other",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "reason",
        "type": "bytes"
      }
    ],
    "name": "CallbackFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCallback",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "operation",
        "type": "bytes4"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "other",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "InvalidCallbackResult",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "position",
        "type": "uint256"
      }
    ],
    "name": "InvalidTypeDescriptor",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct CollectionOperators.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "distinctValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct CollectionOperators.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "filterValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes[][]",
        "name": "values",
        "type": "bytes[][]"
      }
    ],
    "name": "flattenValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "accumulatorType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes",
        "name": "initial",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct CollectionOperators.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "foldValues",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "result",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "outputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct CollectionOperators.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "mapValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "elementType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      }
    ],
    "name": "packArray",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct CollectionOperators.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "sortValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "elementType",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "encoded",
        "type": "bytes"
      }
    ],
    "name": "unpackArray",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "valueType",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "value",
        "type": "bytes"
      }
    ],
    "name": "validateValue",
    "outputs": [],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;
