// Generated by scripts/export-deploy-artifact.mjs — do not edit by hand.
export const COLLECTIONS_ABI = [
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "operation",
        "type": "bytes4"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "other",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "reason",
        "type": "bytes"
      }
    ],
    "name": "CallbackFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCallback",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "operation",
        "type": "bytes4"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "other",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "InvalidCallbackResult",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "head",
        "type": "bytes32"
      }
    ],
    "name": "InvalidComponentEnvelope",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expectedBytes",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "actualBytes",
        "type": "uint256"
      }
    ],
    "name": "InvalidComponentLength",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidComponentValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "which",
        "type": "uint256"
      }
    ],
    "name": "InvalidLane",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "position",
        "type": "uint256"
      }
    ],
    "name": "InvalidTypeDescriptor",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "callData",
        "type": "bytes"
      }
    ],
    "name": "LambdaCallFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "templateLength",
        "type": "uint256"
      }
    ],
    "name": "LambdaOffsetOutOfBounds",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "LambdaReturnTooShort",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "UnalignedWords",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "aWords",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "bWords",
        "type": "uint256"
      }
    ],
    "name": "WordCountMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct Collections.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "distinctValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct Collections.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "filterValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "template",
        "type": "bytes"
      },
      {
        "internalType": "uint256[]",
        "name": "elemOffsets",
        "type": "uint256[]"
      }
    ],
    "name": "filterWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes[][]",
        "name": "values",
        "type": "bytes[][]"
      }
    ],
    "name": "flattenValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "template",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "accOffset",
        "type": "uint256"
      },
      {
        "internalType": "uint256[]",
        "name": "elemOffsets",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes32",
        "name": "init",
        "type": "bytes32"
      },
      {
        "internalType": "enum Collections.FoldExit",
        "name": "exit",
        "type": "uint8"
      }
    ],
    "name": "foldBytes",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "n",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "template",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "accOffset",
        "type": "uint256"
      },
      {
        "internalType": "uint256[]",
        "name": "elemOffsets",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes32",
        "name": "init",
        "type": "bytes32"
      },
      {
        "internalType": "enum Collections.FoldExit",
        "name": "exit",
        "type": "uint8"
      }
    ],
    "name": "foldRange",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "accumulatorType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes",
        "name": "initial",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct Collections.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "foldValues",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "result",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "template",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "accOffset",
        "type": "uint256"
      },
      {
        "internalType": "uint256[]",
        "name": "elemOffsets",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes32",
        "name": "init",
        "type": "bytes32"
      },
      {
        "internalType": "enum Collections.FoldExit",
        "name": "exit",
        "type": "uint8"
      }
    ],
    "name": "foldWords",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "n",
        "type": "uint256"
      }
    ],
    "name": "iotaWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "out",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "outputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct Collections.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "mapValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "template",
        "type": "bytes"
      },
      {
        "internalType": "uint256[]",
        "name": "elemOffsets",
        "type": "uint256[]"
      }
    ],
    "name": "mapWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "elementType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      }
    ],
    "name": "packArray",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      }
    ],
    "name": "reverseWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "out",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "inputType",
        "type": "string"
      },
      {
        "internalType": "bytes[]",
        "name": "values",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "target",
            "type": "address"
          },
          {
            "internalType": "bytes4",
            "name": "selector",
            "type": "bytes4"
          },
          {
            "internalType": "string",
            "name": "arguments",
            "type": "string"
          },
          {
            "internalType": "bytes[]",
            "name": "constants",
            "type": "bytes[]"
          },
          {
            "internalType": "uint256",
            "name": "first",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "second",
            "type": "uint256"
          }
        ],
        "internalType": "struct Collections.Callback",
        "name": "cb",
        "type": "tuple"
      }
    ],
    "name": "sortValues",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "out",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      }
    ],
    "name": "sortWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "out",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      }
    ],
    "name": "sumWords",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "total",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "bool",
        "name": "ordered",
        "type": "bool"
      }
    ],
    "name": "uniqueWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "out",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "elementType",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "encoded",
        "type": "bytes"
      }
    ],
    "name": "unpackArray",
    "outputs": [
      {
        "internalType": "bytes[]",
        "name": "",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "which",
        "type": "uint256"
      }
    ],
    "name": "unzipWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "out",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "valueType",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "value",
        "type": "bytes"
      }
    ],
    "name": "validateValue",
    "outputs": [],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "s",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "w",
        "type": "bytes32"
      }
    ],
    "name": "wordIndexOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "a",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "b",
        "type": "bytes"
      }
    ],
    "name": "zipWords",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "out",
        "type": "bytes"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;
