// Generated by scripts/export-deploy-artifact.mjs, do not edit by hand.
export const EXPRESSIONS_ABI = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "expected",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "actual",
        "type": "uint256"
      }
    ],
    "name": "ComponentCountMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "callData",
        "type": "bytes"
      }
    ],
    "name": "DidNotRevert",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "operation",
        "type": "bytes4"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "other",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "InvalidCallbackResult",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "head",
        "type": "bytes32"
      }
    ],
    "name": "InvalidComponentEnvelope",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expectedBytes",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "actualBytes",
        "type": "uint256"
      }
    ],
    "name": "InvalidComponentLength",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidComponentValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "node",
        "type": "uint256"
      }
    ],
    "name": "InvalidNode",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "node",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "ref",
        "type": "uint256"
      }
    ],
    "name": "InvalidReference",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "node",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "InvalidTarget",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "position",
        "type": "uint256"
      }
    ],
    "name": "InvalidTypeDescriptor",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      }
    ],
    "name": "InvalidValue",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "node",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "callData",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "reason",
        "type": "bytes"
      }
    ],
    "name": "NodeCallFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "NotSelf",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "expected",
        "type": "bytes4"
      },
      {
        "internalType": "bytes4",
        "name": "actual",
        "type": "bytes4"
      }
    ],
    "name": "UnexpectedRevertData",
    "type": "error"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "core",
            "type": "address"
          },
          {
            "components": [
              {
                "internalType": "enum Expressions.Kind",
                "name": "kind",
                "type": "uint8"
              },
              {
                "internalType": "string",
                "name": "valueType",
                "type": "string"
              },
              {
                "internalType": "bytes",
                "name": "data",
                "type": "bytes"
              },
              {
                "internalType": "uint256[]",
                "name": "refs",
                "type": "uint256[]"
              },
              {
                "internalType": "bytes4",
                "name": "selector",
                "type": "bytes4"
              },
              {
                "internalType": "string",
                "name": "arguments",
                "type": "string"
              }
            ],
            "internalType": "struct Expressions.Node[]",
            "name": "nodes",
            "type": "tuple[]"
          },
          {
            "internalType": "uint256",
            "name": "result",
            "type": "uint256"
          }
        ],
        "internalType": "struct Expressions.Expression",
        "name": "expression",
        "type": "tuple"
      },
      {
        "internalType": "bytes[]",
        "name": "parameters",
        "type": "bytes[]"
      }
    ],
    "name": "evaluate",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "expression",
        "type": "bytes"
      },
      {
        "internalType": "bytes[]",
        "name": "parameters",
        "type": "bytes[]"
      }
    ],
    "name": "evaluateEncoded",
    "outputs": [],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "core",
            "type": "address"
          },
          {
            "components": [
              {
                "internalType": "enum Expressions.Kind",
                "name": "kind",
                "type": "uint8"
              },
              {
                "internalType": "string",
                "name": "valueType",
                "type": "string"
              },
              {
                "internalType": "bytes",
                "name": "data",
                "type": "bytes"
              },
              {
                "internalType": "uint256[]",
                "name": "refs",
                "type": "uint256[]"
              },
              {
                "internalType": "bytes4",
                "name": "selector",
                "type": "bytes4"
              },
              {
                "internalType": "string",
                "name": "arguments",
                "type": "string"
              }
            ],
            "internalType": "struct Expressions.Node[]",
            "name": "nodes",
            "type": "tuple[]"
          },
          {
            "internalType": "uint256",
            "name": "result",
            "type": "uint256"
          }
        ],
        "internalType": "struct Expressions.Expression",
        "name": "expression",
        "type": "tuple"
      },
      {
        "internalType": "bytes[]",
        "name": "parameters",
        "type": "bytes[]"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "components": [
          {
            "internalType": "bytes[]",
            "name": "values",
            "type": "bytes[]"
          },
          {
            "internalType": "bool[]",
            "name": "ready",
            "type": "bool[]"
          },
          {
            "internalType": "bool[]",
            "name": "dynamic",
            "type": "bool[]"
          },
          {
            "internalType": "uint256[]",
            "name": "words",
            "type": "uint256[]"
          }
        ],
        "internalType": "struct Expressions.Cache",
        "name": "initial",
        "type": "tuple"
      }
    ],
    "name": "evaluateGuarded",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "result",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes[]",
            "name": "values",
            "type": "bytes[]"
          },
          {
            "internalType": "bool[]",
            "name": "ready",
            "type": "bool[]"
          },
          {
            "internalType": "bool[]",
            "name": "dynamic",
            "type": "bool[]"
          },
          {
            "internalType": "uint256[]",
            "name": "words",
            "type": "uint256[]"
          }
        ],
        "internalType": "struct Expressions.Cache",
        "name": "updated",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
