#!/usr/bin/env python3
"""Retained exact-bytecode public lazy cond input class and exhaustive native dependency closure."""
import sys,os,json,re,shutil,concurrent.futures,threading,importlib.util,datetime,subprocess,csv
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[3]
def module(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
g=module('control',ROOT/'formal/bytecode/assertions-primitives-control/verify.py');getter=g.getter;common=g.common;sha=g.sha
out=Path(sys.argv[1]).resolve();out.mkdir(parents=True,exist_ok=False);closure=g.graph(HERE/'Entry.dfy');snapshot=out/'source-snapshot';control=HERE.parent;primitives=ROOT/'formal/bytecode/assertions-primitives';element=control/'gather-composition';raw=ROOT/'formal/bytecode/assertions-resolution/raw';files=set(closure)|set(getter.inputs())|{f for d in [HERE,control,primitives,element,raw] for f in d.iterdir() if f.is_file()}|{ROOT/'formal/bytecode/unknown/format-generated.py',control/'evidence/20261002-v1/evm-traces/condition-1.json'};hashes={str(f.relative_to(ROOT)):sha(f) for f in sorted(files)}
for f in files:
 target=snapshot/f.relative_to(ROOT);target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(f,target)
dafny=Path('/home/sem/assertions-tools/dafny/dafny');node=Path('/home/sem/assertions-tools/node-v24.14.0-linux-x64/bin/node');solc=Path('/home/sem/assertions-tools/solc-0.8.36');tools={'dafny':dafny,'Dafny.dll':dafny.parent/'Dafny.dll','z3':dafny.parent/'z3/bin/z3-4.12.1','solc':solc,'node':node};os.environ['DAFNY']=str(dafny);lock=threading.Lock();manifest={'schemaVersion':1,'status':'incomplete','startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'contracts':['Assertions'],'scope':'Exact physical public cond class from fresh PC0 through value/selector dispatch and all three InputParam head bounds; RAW zero-constraints condition of arbitrary admitted length; exact ReturnDataOutOfBounds(0,length) for short condition; otherwise first-word zero/nonzero chooses only the selected RAW zero-constraints operand and physically returns its original bytes. No validity premise is imposed on the unselected operand beyond its public decoder head span. Arbitrary offset relocation, aliasing and trailing calldata are admitted by the independent specification. Other fetchers, nonempty constraints, malformed outer heads and whole cond/whole Assertions remain open.','publicEntries':[{'name':'cond','selector':'0x5fe917dc','class':'condition RAW zero-constraints; either short-condition rejection or selected RAW zero-constraints success; msg.value0 and explicit resource bounds','specification':'AssertionsCondRawAdmission.Calldata','theorem':'AssertionsCondRawPublicConnection.Run','result':'original selected calldata payload or exact ReturnDataOutOfBounds(0,length)','wholeEntry':False}],'includeClosure':[str(f.relative_to(ROOT)) for f in closure],'sourceSha256':hashes,'versions':{k:subprocess.check_output([str(v),'--version'],text=True).strip() for k,v in tools.items() if k!='Dafny.dll'},'executableSha256':{k:sha(v) for k,v in tools.items()},'proofMode':'Fresh per-file native verification with exact file/module filters and exhaustive declaration coverage. Helpers globally isolated in development context; unchanged RAW helper normal verification120s.','checks':[],'assumptions':['Reviewed reached EVM interpretation and physical runtime extraction; solc/Dafny/Boogie/Z3 and pinned concrete tools are trusted. Adequate gas/memory/execution resources are explicit premises.','Fresh frame starts at PC0 with empty stack/memory/returndata, observation cursor0 and msg.value0. All three public head pointers satisfy actual nonwrapping64bit bounds. Condition is independently RAW/no-constraints; successful class also requires only selected operand RAW/no-constraints and allocator budget.','Payload bytes and first condition word are specified directly from original calldata. No precondition supplies correctly decoded, resolved or returned results. This is a completed public input class once gates pass, not a whole-entry or whole-contract proof.']}
assert manifest['versions']['dafny']==json.loads((ROOT/'formal/abi/toolchain.json').read_text())['dafnyVersion'] and '4.12.1' in manifest['versions']['z3'] and '0.8.36+commit.8a079791' in manifest['versions']['solc']
def save():
 with lock:(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
def record(name,cmd,timeout=7200):
 job=common.run(cmd,out/(name+'.log'),timeout);job.update(name=name,passed=job['exitCode']==0)
 with lock:manifest['checks'].append(job)
 save();return job
save();record('runtime-identity',[sys.executable,'-B',snapshot/'formal/bytecode/dispatch/identity.py','--contract','Assertions','--solc',solc,'--output',out/'identity'],300);record('literal-runtime-binding',[sys.executable,'-B',snapshot/HERE.relative_to(ROOT)/'binding.py',snapshot,out/'manifest.json'],300)
regen=out/'regeneration';shutil.copytree(snapshot,regen);at=lambda path:regen/path.relative_to(ROOT)
record('generation-control',[sys.executable,'-B',at(control)/'generate.py','--output',at(control)],300)
record('generation-public',[sys.executable,'-B',at(HERE)/'generate.py'],300)
for name in ['Dispatch','Decoder']:record('format-public-'+name,[dafny,'format',at(HERE)/(name+'.generated.dfy')],300)
record('generation-leaves',[sys.executable,'-B',at(HERE)/'generate-leaves.py'],300)
record('generation-raw',[sys.executable,'-B',at(raw)/'generate.py','--output',at(raw)],300);record('format-raw',[dafny,'format',at(raw)/'Raw.generated.dfy'],300)
compared=[f for f in files if f.suffix=='.dfy' or f.name.endswith('.mapping.json') or f.name=='leaf-provenance.json'];manifest['generationIdentical']=all(at(f).read_bytes()==(snapshot/f.relative_to(ROOT)).read_bytes() for f in compared);save()
if not manifest['generationIdentical'] or not all(x['passed'] for x in manifest['checks']):manifest['status']='failed';save();raise SystemExit('Identity/generation failed; diagnostics retained')
def prove(f):
 name=re.search(r'^module (\w+)',f.read_text(),re.M)[1];file=snapshot/f.relative_to(ROOT);csvfile=out/('proof-'+name+'.csv');cmd=common.proof_command(dafny,file,csvfile);cmd[cmd.index('--cores')+1]='1'
 if f==raw/'Raw.generated.dfy':cmd.remove('--isolate-assertions');cmd[cmd.index('--verification-time-limit')+1]='120'
 cmd+=['--filter-symbol',name,'--filter-position',str(file),'--progress','Symbol'];job=record('proof-'+name,cmd);common.check_proof(job,out/('proof-'+name+'.log'),csvfile,getter.inventory(f));save();print(name,len(job['nativeResults']),'passed' if job['passed'] else 'FAILED',flush=True);return job
with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:jobs=list(pool.map(prove,[f for f in closure if re.search(r'^module (\w+)',f.read_text(),re.M)]))
manifest['nativeResults']=[r for job in jobs for r in job['nativeResults']];manifest['declarationResults']=[d for job in jobs for d in job['declarations']];save()
audit=record('audit',[dafny,'audit',snapshot/HERE.relative_to(ROOT)/'Entry.dfy'],300);audit['passed'] &= 'auditor completed with 0 findings' in (out/'audit.log').read_text();record('format',[dafny,'format','--check',*[snapshot/f.relative_to(ROOT) for f in closure]],300)
concrete=record('concrete',[node,HERE/'evm-traces.mjs','--root',snapshot,'--output',out/'evm-traces'],300);rows=json.loads((out/'evm-traces/results.json').read_text());concrete['passed'] &= len(rows)==34 and all(x['passed'] for x in rows);manifest['concreteToolchain']=json.loads((out/'evm-traces/toolchain.json').read_text());save()
mutation=out/'mutations/choose-else';mutation.mkdir(parents=True);target=control/'CondTrue.generated.dfy';candidateSource=mutation/'source-snapshot'
for f in g.graph(target):
 dst=candidateSource/f.relative_to(ROOT);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(snapshot/f.relative_to(ROOT),dst)
file=candidateSource/target.relative_to(ROOT);text=file.read_text();assert text.count('code[1824] == 132')==1 and text.count('assert Fetch(code,1824) == Op(132,1825,0);')==1;file.write_text(text.replace('code[1824] == 132','code[1824] == 131').replace('assert Fetch(code,1824) == Op(132,1825,0);','assert Fetch(code,1824) == Op(131,1825,0);'));csvfile=mutation/'proof.csv';cmd=common.proof_command(dafny,file,csvfile);cmd[cmd.index('--cores')+1]='1';cmd+=['--filter-symbol','AssertionsControlCondTrue.Advance6.','--filter-position',str(file),'--progress','Symbol'];job=record('mutation-native-choose-else',cmd,300);text=(out/'mutation-native-choose-else.log').read_text();results=list(csv.DictReader(csvfile.open())) if csvfile.exists() else [];job['passed']=job['exitCode'] not in [0,None] and bool(results) and any(x['TestResult.Outcome']=='Failed' for x in results) and all(x['TestResult.Outcome'] in {'Passed','Failed'} for x in results) and 'postcondition could not be proved' in text and 'assertion might not hold' not in text and not re.search(r'timed out|inconclusive|resource limit|parse error|resolution/type error',text);job['expectedSemanticFailure']=True;job['nativeResults']=results
baseline=next(x for x in jobs if x['name']=='proof-AssertionsControlCondTrue');assert next(x for x in baseline['declarations'] if x['name']=='AssertionsControlCondTrue.Advance6')['status']=='passed';runtime=bytes.fromhex(json.loads((snapshot/'artifacts/contracts/Assertions.sol/Assertions.json').read_text())['deployedBytecode'][2:]);assert runtime[1824]==132;mutated=bytearray(runtime);mutated[1824]=131;candidate=mutation/'runtime.bin';candidate.write_bytes(mutated);job=record('mutation-complete-public-receipt-choose-else',[node,HERE/'evm-traces.mjs','--root',snapshot,'--runtime',candidate,'--case','mutation-both-raw','--output',mutation/'evm'],300);rows=json.loads((mutation/'evm/results.json').read_text());job['passed']=job['exitCode'] not in [0,None] and len(rows)==1 and rows[0]['classPassed'] and not rows[0]['receiptPassed'] and not rows[0]['actualFailed'];job['expectedSemanticFailure']=True;manifest['mutation']={'runtimeByte':1824,'before':132,'after':131,'baselineDeclaration':'AssertionsControlCondTrue.Advance6','nativeSourceSha256':sha(file),'runtimeSha256':sha(candidate),'completePublicReceiptCase':'mutation-both-raw','correctPhysicalMutantFetchCertificate':True}
manifest['inputsUnchanged']=all(sha(ROOT/f)==h and sha(snapshot/f)==h for f,h in hashes.items());manifest['toolsUnchanged']=all(sha(v)==manifest['executableSha256'][k] for k,v in tools.items());ct=manifest['concreteToolchain'];manifest['concreteToolsUnchanged']=all(sha(Path(ct[k]))==ct[k+'Sha256'] for k in ['hardhatEntry','edrEntry','nativeBinding']) and sha(Path(ct['nodeExecutable']))==ct['nodeSha256'] and sha(ROOT/'pnpm-lock.yaml')==ct['lockfileSha256'];manifest['status']='passed' if manifest['inputsUnchanged'] and manifest['toolsUnchanged'] and manifest['concreteToolsUnchanged'] and manifest['generationIdentical'] and all(job['passed'] for job in manifest['checks']) else 'failed';manifest['finishedAt']=datetime.datetime.now(datetime.timezone.utc).isoformat();save();manifest['evidenceSha256']={str(f.relative_to(out)):sha(f) for f in out.rglob('*') if f.is_file() and f.name!='manifest.json' and 'source-snapshot' not in f.parts};save();print(manifest['status'],len(manifest['nativeResults']),flush=True);raise SystemExit(0 if manifest['status']=='passed' else 1)
