import hashlib,json,subprocess,sys
from pathlib import Path
root=Path.cwd();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
base=root/'formal/source/evidence/restructured-closures-v1';campaign=json.loads((base/'manifest.json').read_text());native=next(x for x in campaign['checks'] if x['name']=='concat');assert native['passed']
assert native['sourceBefore']==native['sourceAfter'];assert campaign['toolsBefore']==native['toolsAfter'];assert all(c['passed'] and c['exitCode']==0 for c in native['checks'])
concrete=root/'formal/source/evidence/concat-edr-v2/results.json';c=json.loads(concrete.read_text());assert len(c['tests'])==2 and all(t['passed'] for t in c['tests'])
faults=root/'formal/source/evidence/concat-source-faults-edr-v2/results.json';f=json.loads(faults.read_text());assert f['status']=='passed' and len(f['results'])==2 and all(k['passed'] for r in f['results'] for k in r['checks'])
legacy=root/'docs/verification/operations-concat-source.json';l=json.loads(legacy.read_text());generator=root/'formal/operations/concat/generate.py';new=root/'formal/source/operations/concat/v1';mapping=json.loads((new/'mapping.json').read_text())
for p,h in mapping['sourceSha256'].items():assert sha(root/p)==h
for p,h in c['sourceSha256'].items():assert sha(root/p)==h
snapshot=root/'formal/source/evidence/concat-correspondence-v1/snapshot';assert (snapshot/'formal/source/operations/concat/v1/Model.dfy').read_bytes()==(new/'Model.dfy').read_bytes()
for name in ['Model.dfy','Connection.dfy','Control.generated.dfy']:assert (snapshot/'formal/source/operations/concat/v1'/name).read_bytes()==(new/name).read_bytes()
result={'status':'candidate-complete-conditional-source-gates-awaiting-independent-review','scope':l['scope'],'originalLedger':{'path':str(legacy.relative_to(root)),'sha256':sha(legacy)},'originalAssumptions':l['assumptions'],'publicEntry':l['entries'],'bytecodeEquivalence':'NOT_PROVED','native':{'campaignManifest':str((base/'manifest.json').relative_to(root)),'campaignManifestSha256':sha(base/'manifest.json'),'package':'concat','nativeBatches':307,'toolsBefore':campaign['toolsBefore'],'toolsAfter':native['toolsAfter'],'completeClosureBefore':native['sourceBefore'],'completeClosureAfter':native['sourceAfter'],'auditFindings':0,'formatPassed':True,'note':'Overall five-package campaign failed solely first Expressions typecheck; concat subpackage native/audit/format/tool/source gates passed. No overall campaign pass claimed.'},'mapping':{'path':'formal/source/theorem-mapping.json','sha256':sha(root/'formal/source/theorem-mapping.json')},'sourceGeneration':{'originalGeneratorPath':str(generator.relative_to(root)),'originalGeneratorSha256':sha(generator),'productionMappingPath':str((new/'mapping.json').relative_to(root)),'productionMappingSha256':sha(new/'mapping.json'),'freshOriginalASTGeneratedAdapterSha256':sha(new/'Control.generated.dfy')},'concrete':{'engine':'Hardhat/EDR, not Forge','receipt':str(concrete.relative_to(root)),'receiptSha256':sha(concrete),'tests':c['tests'],'compileReceipt':'formal/source/evidence/concat-compile-v2/compile-receipt.json','compileReceiptSha256':sha(root/'formal/source/evidence/concat-compile-v2/compile-receipt.json')},'faults':{'receipt':str(faults.relative_to(root)),'receiptSha256':sha(faults),'semanticSourceFaults':2},'failuresPreserved':['formal/source/evidence/concat-v1','formal/source/evidence/concat-correspondence-v1/concrete.log','formal/source/evidence/concat-source-faults-edr-v1'],'newFoundation':'Independent total-memory cell/replacement/outside proofs; original total-memory representation and complete CopyProjection requirements/conclusions preserved'}
output=root/'formal/source/evidence/concat-source-candidate-v1.json';assert not output.exists();output.write_text(json.dumps(result,indent=2)+'\n');print(output)
