// SPDX-License-Identifier: MIT
// GENERATED by aggregate/generate.py; do not edit.
// Source SHA-256: 485f0d49f35528cc4c9be7767c631be6903ff57b5cb95bcbb25d6cd04ce5fed6
include "CursorSemantics.dfy"

module AbiCursorSource {
  import opened AbiFrames
  import opened AbiEncoding
  import opened AbiValidation
  import opened AbiByteSemantics
  import opened AbiBytesSource
  import opened AbiCursorSemantics

  ghost method {:isolate_assertions} ArrayHead(v: seq<Byte>, base: nat, count: nat, words: nat) returns (r: Outcome)
    requires Uint(|v|) && base <= |v| && Uint(count) && Uint(words) && words > 0
    ensures r == (if count*words*32 > |v|-base then Invalid(base) else Ok(count*words*32))
  {
    DivisionBound(|v|-base,count,words);
    var tail: int := 0;
    // solc AST 1368 @ 25681:76:0
    var tmp1: int := |v| - base;
    if !Uint(tmp1) { r := Panic(17); return; }
    if 32 == 0 { r := Panic(18); return; }
    DivisionShrinks(tmp1,32);
    if 32 == 0 { r := Panic(18); return; }
    var tmp2: int := tmp1 / 32;
    if !Uint(tmp2) { r := Panic(17); return; }
    if words == 0 { r := Panic(18); return; }
    DivisionShrinks(tmp2,words);
    if words == 0 { r := Panic(18); return; }
    var tmp3: int := tmp2 / words;
    if !Uint(tmp3) { r := Panic(17); return; }
    if !((count <= tmp3)) {
      r := Invalid(base); return;
    }
    ProductFits(count,words,|v|-base);
    // solc AST 1380 @ 25771:31:0
    var tmp4: int := count * words;
    if !Uint(tmp4) { r := Panic(17); return; }
    var tmp5: int := tmp4 * 32;
    if !Uint(tmp5) { r := Panic(17); return; }
    tail := tmp5;
    r := Ok(tail);
  }
  ghost method TupleHeadStep(v: seq<Byte>, p: nat, previous: nat, w: nat) returns (r: Outcome)
    requires Uint(|v|) && p+previous <= |v| && Uint(w) && w > 0
    ensures r == (if w*32 > |v|-p-previous then Invalid(p) else Ok(previous+w*32))
  {
    DivisionBound(|v|-p-previous,w,1);
    var tail: int := previous;
    // solc AST 1524 @ 26603:59:0
    var tmp6: int := |v| - p;
    if !Uint(tmp6) { r := Panic(17); return; }
    var tmp7: int := tmp6 - tail;
    if !Uint(tmp7) { r := Panic(17); return; }
    if 32 == 0 { r := Panic(18); return; }
    DivisionShrinks(tmp7,32);
    if 32 == 0 { r := Panic(18); return; }
    var tmp8: int := tmp7 / 32;
    if !Uint(tmp8) { r := Panic(17); return; }
    if !((w <= tmp8)) {
      r := Invalid(p); return;
    }
    // solc AST 1532 @ 26680:16:0
    var tmp9: int := w * 32;
    if !Uint(tmp9) { r := Panic(17); return; }
    var tmp10: int := tail + tmp9;
    if !Uint(tmp10) { r := Panic(17); return; }
    tail := tmp10;
    r := Ok(tail);
  }
  ghost method ArrayPosition(v: seq<Byte>, base: nat, count: nat, words: nat, i: nat) returns (r: Outcome)
    requires Uint(|v|) && words > 0 && i < count && base+count*words*32 <= |v|
    ensures r == Ok(base+i*words*32)
    ensures r.used+32*words <= |v|
  {
    PositionFits(base,count,words,i,|v|);
    // solc AST 1428 @ 26128:44:0
    var tmp11: int := i * words;
    if !Uint(tmp11) { r := Panic(17); return; }
    var tmp12: int := tmp11 * 32;
    if !Uint(tmp12) { r := Panic(17); return; }
    var tmp13: int := base + tmp12;
    if !Uint(tmp13) { r := Panic(17); return; }
    var position := tmp13;
    r := Ok(position);
  }
  ghost method ArrayOffset(v: seq<Byte>, position: nat, tail: nat) returns (r: Outcome)
    requires Uint(|v|) && position+32 <= |v| && Uint(tail)
    ensures r == (if ReadNat(v[position..position+32]) == tail then Ok(0) else Invalid(position))
  {
    // solc AST 1441 @ 26190:69:0
    var tmp14 := ReadWord(v,position);
    if !tmp14.Ok? { r := tmp14; return; }
    if !((tmp14.used == tail)) {
      r := Invalid(position); return;
    }
    r := Ok(0);
  }
  ghost method TupleOffset(v: seq<Byte>, p: nat, base: nat, tail: nat) returns (r: Outcome)
    requires Uint(|v|) && p+base+32 <= |v| && Uint(tail)
    ensures r == (if ReadNat(v[p+base..p+base+32]) == tail then Ok(0) else Invalid(p+base))
  {
    // solc AST 1591 @ 26938:73:0
    var tmp15: int := p + base;
    if !Uint(tmp15) { r := Panic(17); return; }
    var tmp16 := ReadWord(v,tmp15);
    if !tmp16.Ok? { r := tmp16; return; }
    var tmp17: int := p + base;
    if !Uint(tmp17) { r := Panic(17); return; }
    if !((tmp16.used == tail)) {
      r := Invalid(tmp17); return;
    }
    r := Ok(0);
  }
  ghost method ArrayTailAdvance(v: seq<Byte>, base: nat, previous: nat, used: nat) returns (r: Outcome)
    requires Uint(|v|) && base+previous+used <= |v|
    ensures r == Ok(previous+used)
  {
    var tail: int := previous;
    // solc AST 1459 @ 26277:54:0
    var tmp18: int := base + tail;
    if !Uint(tmp18) { r := Panic(17); return; }
    assert tmp18+used <= |v|;
    var tmp19: int := tail + used;
    if !Uint(tmp19) { r := Panic(17); return; }
    tail := tmp19;
    r := Ok(tail);
  }
  ghost method TupleTailAdvance(v: seq<Byte>, p: nat, previous: nat, used: nat) returns (r: Outcome)
    requires Uint(|v|) && p+previous+used <= |v|
    ensures r == Ok(previous+used)
  {
    var tail: int := previous;
    // solc AST 1608 @ 27033:52:0
    var tmp20: int := p + tail;
    if !Uint(tmp20) { r := Panic(17); return; }
    assert tmp20+used <= |v|;
    var tmp21: int := tail + used;
    if !Uint(tmp21) { r := Panic(17); return; }
    tail := tmp21;
    r := Ok(tail);
  }
}
