#!/usr/bin/env python3
"""Retain the exact PC0 -> RETURN public empty-gather class, with whole closure."""
import sys,os,json,re,shutil,concurrent.futures,threading,importlib.util,datetime,subprocess
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[3]
def module(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
g=module('control',ROOT/'formal/bytecode/assertions-primitives-control/verify.py');getter=g.getter;common=g.common;sha=g.sha
out=Path(sys.argv[1]).resolve();out.mkdir(parents=True,exist_ok=False);closure=g.graph(HERE/'Entry.dfy');snapshot=out/'source-snapshot';files=set(closure)|set(getter.inputs())|{f for f in HERE.iterdir() if f.is_file()}|{HERE/'fixtures/empty-canonical.json',HERE.parent/'GatherStartZero.mapping.json',HERE.parent/'GatherDoneExit.mapping.json',ROOT/'formal/bytecode/unknown/format-generated.py'};hashes={str(f.relative_to(ROOT)):sha(f) for f in sorted(files)}
for f in files:
 target=snapshot/f.relative_to(ROOT);target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(f,target)
dafny=Path('/home/sem/assertions-tools/dafny/dafny');node=Path('/home/sem/assertions-tools/node-v24.14.0-linux-x64/bin/node');solc=Path('/home/sem/assertions-tools/solc-0.8.36');lock=threading.Lock();manifest={'schemaVersion':1,'status':'incomplete','startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'contracts':['Assertions'],'scope':'Exact physical public gather empty-array class: fresh PC0, actual selector/value dispatcher, arbitrary admitted top-array relative offset and trailing calldata, actual Param[] decoder, actual zero-count body and standard 64-byte empty bytes[] return. The decoder separately accepts arbitrary bounded counts; nonempty serialization and full gather/whole contract remain open.','publicEntries':[{'name':'gather','selector':'0x6db7211f','class':'admitted zero-count array, zero msg.value','specification':'AssertionsGatherEmptyPublicConnection.Calldata','theorem':'AssertionsGatherEmptyPublicConnection.Run','wholeEntry':False}],'includeClosure':[str(f.relative_to(ROOT)) for f in closure],'sourceSha256':hashes,'versions':{k:subprocess.check_output([str(v),'--version'],text=True).strip() for k,v in {'dafny':dafny,'z3':dafny.parent/'z3/bin/z3-4.12.1','solc':solc,'node':node}.items()},'executableSha256':{k:sha(v) for k,v in {'dafny':dafny,'Dafny.dll':dafny.parent/'Dafny.dll','z3':dafny.parent/'z3/bin/z3-4.12.1','solc':solc,'node':node}.items()},'checks':[],'assumptions':['Reviewed reached instruction semantics, exact compiler identity and actual full-runtime instruction-boundary scanner are trusted; sufficient execution resources are premises.','Fresh initial machine state has an empty stack/memory, empty returndata and observation cursor zero; msg.value is zero. Public calldata obeys the independent accepted empty-array layout, but its relative offset and trailing bytes are arbitrary.','Dafny/Boogie/Z3, solc, Node/Hardhat/EDR and evidence scripts are trusted. This is a public-entry input class, not a whole-entry or whole-contract proof.']}
def save():
 with lock:(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
def record(name,cmd,timeout=7200):
 job=common.run(cmd,out/(name+'.log'),timeout);job.update(name=name,passed=job['exitCode']==0)
 with lock:manifest['checks'].append(job)
 save();return job
save();record('runtime-identity',[sys.executable,'-B',snapshot/'formal/bytecode/dispatch/identity.py','--contract','Assertions','--solc',solc,'--output',out/'identity'],300)
regen=out/'regeneration';shutil.copytree(snapshot,regen);source=regen/HERE.relative_to(ROOT);record('generation',[sys.executable,'-B',source/'generate.py'],300)
for f in ['Dispatch','Decoder','EmptySerializer']:record('generation-format-'+f,[dafny,'format',source/(f+'.generated.dfy')],300)
manifest['generationIdentical']=all((source/(f+s)).read_bytes()==(snapshot/HERE.relative_to(ROOT)/(f+s)).read_bytes() for f in ['Dispatch','Decoder','EmptySerializer'] for s in ['.generated.dfy','.mapping.json']);save()
def prove(f):
 name=re.search(r'^module (\w+)',f.read_text(),re.M)[1];csv=out/('proof-'+name+'.csv');cmd=common.proof_command(dafny,snapshot/f.relative_to(ROOT),csv);cmd[cmd.index('--cores')+1]='1';cmd+=['--filter-symbol',name,'--progress','Symbol'];job=record('proof-'+name,cmd);common.check_proof(job,out/('proof-'+name+'.log'),csv,getter.inventory(f));save();print(name,len(job['nativeResults']),'passed' if job['passed'] else 'FAILED',flush=True);return job
with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:jobs=list(pool.map(prove,[f for f in closure if re.search(r'^module (\w+)',f.read_text(),re.M)]))
manifest['nativeResults']=[r for j in jobs for r in j['nativeResults']];manifest['declarationResults']=[d for j in jobs for d in j['declarations']]
audit=record('audit',[dafny,'audit',snapshot/HERE.relative_to(ROOT)/'Entry.dfy'],300);audit['passed'] &= 'auditor completed with 0 findings' in (out/'audit.log').read_text();record('format',[dafny,'format','--check',*[snapshot/f.relative_to(ROOT) for f in closure]],300)
concrete=record('concrete',[node,HERE/'evm-traces.mjs','--root',snapshot,'--output',out/'evm-traces'],300);rows=json.loads((out/'evm-traces/results.json').read_text());concrete['passed'] &= len(rows)==4 and all(x['passed'] for x in rows)
mutations=out/'mutations';mutations.mkdir();runtime=bytes.fromhex(json.loads((snapshot/'artifacts/contracts/Assertions.sol/Assertions.json').read_text())['deployedBytecode'][2:]);assert runtime[17322]==96 and runtime[17323]==32
for value in [32,64]:
 program=mutations/('physical-offset-'+str(value)+'.dfy');program.write_text('// SPDX-License-Identifier: MIT\ninclude "'+str(snapshot/'formal/bytecode/scans/Fetch.dfy')+'"\nmodule PhysicalEmptyArrayOffset {\n import S = BytecodeScanMachine\n import F = BytecodeScanFetch\n lemma PhysicalPush()\n  ensures var code: seq<S.Byte> := seq(17324,i => if i==17322 then 96 else if i==17323 then '+str(value)+' else 0); S.Step(code,{},S.Running(17322,[],[]),0,[]) == S.Running(17324,[32],[])\n {\n  var code: seq<S.Byte> := seq(17324,i => if i==17322 then 96 else if i==17323 then '+str(value)+' else 0);\n  F.Push1(code,17322); reveal S.Step();\n }\n}\n')
 job=record('mutation-native-'+str(value),[dafny,'verify',program,'--filter-symbol','PhysicalEmptyArrayOffset','--verification-time-limit','30','--solver-path',dafny.parent/'z3/bin/z3-4.12.1'],300)
 if value==64:
  log=(out/('mutation-native-'+str(value)+'.log')).read_text();job['passed']=job['exitCode']!=0 and 'postcondition could not be proved' in log and 'timed out' not in log and 'parse error' not in log;job['expectedSemanticFailure']=True
mutated=bytearray(runtime);mutated[17323]=64;candidate=mutations/'offset-64.bin';candidate.write_bytes(mutated);job=record('mutation-complete-receipt',[node,HERE/'evm-traces.mjs','--root',snapshot,'--runtime',candidate,'--case','canonical','--output',mutations/'evm'],300);mutrow=json.loads((mutations/'evm/results.json').read_text());job['passed']=job['exitCode']!=0 and len(mutrow)==1 and not mutrow[0]['receiptPassed'] and not mutrow[0]['actualFailed'];job['expectedSemanticFailure']=True
manifest['inputsUnchanged']=all(sha(ROOT/f)==h for f,h in hashes.items());manifest['status']='passed' if manifest['inputsUnchanged'] and manifest['generationIdentical'] and all(j['passed'] for j in manifest['checks']) else 'failed';manifest['finishedAt']=datetime.datetime.now(datetime.timezone.utc).isoformat();save();manifest['evidenceSha256']={str(f.relative_to(out)):sha(f) for f in out.rglob('*') if f.is_file() and f.name!='manifest.json' and 'source-snapshot' not in f.parts};save();print(manifest['status'],len(manifest['nativeResults']),flush=True);raise SystemExit(0 if manifest['status']=='passed' else 1)
