#!/usr/bin/env python3
"""Generate deterministic independent test vectors; never modifies production sources.
Python arbitrary-precision arithmetic is the numeric oracle. The fixed-point
oracle is the separate generic Horner specification, not the Solidity source.
"""
import importlib.util,json,random,hashlib,sys,subprocess
sys.dont_write_bytecode=True
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
rng=random.Random(20261002);W=1<<256;H=1<<255
spec=importlib.util.spec_from_file_location('rational',ROOT/'scripts/claim-coverage-fixed-point-oracle.py');r=importlib.util.module_from_spec(spec);spec.loader.exec_module(r)
def signed(x):return x if x<H else x-W
def rem(x,m):return (-1 if x<0 else 1)*(abs(x)%abs(m))
def array(rows):return (32).to_bytes(32,'big').hex()+len(rows).to_bytes(32,'big').hex()+''.join((x%W).to_bytes(32,'big').hex() for row in rows for x in row)
mods=[]
for i in range(64):
 a=signed(rng.getrandbits(256));b=signed(rng.getrandbits(256));m=signed(rng.getrandbits(256)) or 1
 if i<8:a=[-H,H-1,-H,-H,0,-1,1,H-1][i];b=[-H,H-1,H-1,-1,H-1,-H,-H,-H][i];m=[7,-H,-7,-H,-1,1,-H,-H][i]
 mods.append([a,b,m,rem(a+b,m),rem(a*b,m)])
powers=[];inverses=[]
for i in range(48):
 a=signed(rng.getrandbits(256));m=signed(rng.getrandbits(256)) or 1;e=[0,1,2,3,(1<<32)-1,1<<32,(1<<32)+1,(1<<255)-1][i%8]
 if i<4:a=-H;m=[-H,-7,1,H-1][i]
 value=pow(abs(a),e,abs(m));value=-value if a<0 and e%2 else value;powers.append([a,e,m,value])
powers += [[-1,W-1,-H,-1],[-H,W-1,-7,-pow(H,W-1,7)],[-3,H+1,H-1,-pow(3,H+1,H-1)]]
for i in range(40):
 a=signed(rng.getrandbits(256));m=signed(rng.getrandbits(256)) or 1;e=-([2,3,7,31,1<<32,1<<255][i%6])
 try:
  value=pow(abs(a),e,abs(m));value=-value if a<0 and (-e)%2 else value
  inverses.append([a,e,m,value,0])
 except ValueError:inverses.append([a,e,m,0,1])
inverses += [[-6,-2,-9,0,1],[0,-3,7,0,1],[-5,-7,-1,0,0],[-H,-3,-7,-pow(H,-3,7),0]]
fixed={}
for name in ['exp','ln']:
 xs=([r.LOW-1,r.LOW,r.LOW+1,r.HIGH-1,r.HIGH,r.HIGH+1,-H,H-1,0,1,-1] if name=='exp' else [-H,-1,0,1,H-1])
 if name=='exp':xs += [rng.randrange(r.LOW,r.HIGH) for _ in range(64)]+[r.trunc(k*r.LN2*10**18,r.Q)+d for k in [-60,-30,0,30,100,190] for d in [-1,0,1]]
 else:xs += [rng.randrange(1,H) for _ in range(64)]+[(1<<k)+d for k in [1,32,64,95,96,97,128,200,254] for d in [-1,0,1]]
 rows=[]
 for x in xs:
  out=getattr(r,name)(x);rows.append([x,out.get('value',out.get('panic',out.get('undefined',0))),0 if 'value'in out else 1 if 'panic'in out else 2])
 fixed[name]=rows
formats=[]
for i in range(40):
 n=rng.getrandbits(256);d=[0,1,2,6,18,38,77][i%7];s=str(n).rjust(d+1,'0')
 text=s if d==0 else s[:-d]+'.'+s[-d:];text=text.rstrip('0').rstrip('.') if d else text
 formats.append([n,d,text])
body='''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by scripts/generate-claim-coverage-vectors.py, seed 20261002.
import "forge-std/Test.sol";
import "../Operations.sol";
contract ClaimCoverageOracleTest is Test {
 Operations ops;
 function setUp() public {ops=new Operations();}
 function failure(bytes memory data,bytes memory expected) internal view {(bool ok,bytes memory out)=address(ops).staticcall(data);assertFalse(ok);assertEq(out,expected);}
'''
body+='function test_O13_FullWidthIndependentPythonRemainders() public view {int256[5][] memory v=abi.decode(hex"'+array(mods)+'",(int256[5][]));for(uint256 i;i<v.length;i++){assertEq(ops.addMod(v[i][0],v[i][1],v[i][2]),v[i][3]);assertEq(ops.mulMod(v[i][0],v[i][1],v[i][2]),v[i][4]);}}\n'
body+='function test_O18_FullWidthSignedBasePowers() public view {int256[4][] memory v=abi.decode(hex"'+array(powers)+'",(int256[4][]));for(uint256 i;i<v.length;i++)assertEq(ops.powMod(v[i][0],uint256(v[i][1]),v[i][2]),v[i][3]);}\n'
body+='function test_O19_FullWidthNegativeExponents() public view {int256[5][] memory v=abi.decode(hex"'+array(inverses)+'",(int256[5][]));for(uint256 i;i<v.length;i++){uint256 a=v[i][0]<0?uint256(-(v[i][0]+1))+1:uint256(v[i][0]);uint256 m=v[i][2]<0?uint256(-(v[i][2]+1))+1:uint256(v[i][2]);if(v[i][4]==0){assertEq(ops.powMod(v[i][0],v[i][1],v[i][2]),v[i][3]);uint256 expected=v[i][3]<0?uint256(-(v[i][3]+1))+1:uint256(v[i][3]);assertEq(ops.powMod(a,v[i][1],m),expected);}else{bytes memory reason=abi.encodeWithSelector(Operations.ModularInverseDoesNotExist.selector,a,m);failure(abi.encodeWithSignature("powMod(int256,int256,int256)",v[i][0],v[i][1],v[i][2]),reason);failure(abi.encodeWithSignature("powMod(uint256,int256,uint256)",a,v[i][1],m),reason);}}failure(abi.encodeWithSignature("powMod(uint256,int256,uint256)",uint256(3),int256(-3),uint256(0)),abi.encodeWithSignature("Panic(uint256)",uint256(18)));failure(abi.encodeWithSignature("powMod(int256,int256,int256)",int256(-3),int256(-3),int256(0)),abi.encodeWithSignature("Panic(uint256)",uint256(18)));}\n'
for name,id in [('exp','O26'),('ln','O27')]:
 body+='function test_'+id+'_GeneratedFiniteWordKernelAndExactErrors() public view {int256[3][] memory v=abi.decode(hex"'+array(fixed[name])+'",(int256[3][]));for(uint256 i;i<v.length;i++){if(v[i][2]==0)assertEq(ops.'+name+'Wad(v[i][0]),v[i][1]);else failure(abi.encodeWithSignature("'+name+'Wad(int256)",v[i][0]),v[i][2]==1?abi.encodeWithSignature("Panic(uint256)",uint256(v[i][1])):abi.encodeWithSelector(Operations.LogarithmUndefined.selector,v[i][0]));}}\n'
body+='function test_O64_O68_IndependentPythonCanonicalFormatVectors() public view {\n'
for n,d,text in formats:
 body+=f'assertEq(ops.formatUnits(uint256({n}),{d}),"{text}");\n'
 val=signed(n);body+=f'assertEq(ops.toString(int256({val})),"{val}");\n'
body+='}\n}\n'
output=ROOT/'contracts/tests/ClaimCoverageOracle.t.sol';output.write_text(body)
subprocess.run(['forge','fmt',str(output)],check=True)
summary={'seed':20261002,'counts':{'O13':len(mods)*2,'O18':len(powers),'O19':len(inverses)*2+2,'O26':len(fixed['exp']),'O27':len(fixed['ln']),'O64':len(formats),'O68':len(formats)},'oracleSha256':hashlib.sha256(Path(r.__file__).read_bytes()).hexdigest()}
Path('/tmp/assertions-coverage-vector-generation.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary))
