#!/usr/bin/env python3
"""Bind getter values and the complete public ABI inventory to fresh solc AST/ABI."""
import argparse, hashlib, json, subprocess
from pathlib import Path
if not __debug__:
    raise RuntimeError('Run without Python -O: source gates use assertions')
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
def canonical(item):
    return '('+','.join(canonical(x) for x in item['components'])+')'+item['type'][5:] if item['type'].startswith('tuple') else item['type']
def signature(item): return item['name']+'('+','.join(canonical(x) for x in item.get('inputs',[]))+')'
def integer(node):
    kind=node['nodeType']
    if kind=='MemberAccess':
        assert node['memberName']=='min'
        call=node['expression'];assert call['nodeType']=='FunctionCall' and call['expression']['name']=='type'
        assert len(call['arguments'])==1 and call['arguments'][0]['nodeType']=='ElementaryTypeNameExpression'
        assert call['arguments'][0]['typeName']['name']=='int256'
        return -(1<<255)
    if kind=='BinaryOperation':
        assert node['operator']=='+' and node['rightExpression']['nodeType']=='Literal' and node['rightExpression']['value']=='1'
        return integer(node['leftExpression'])+1
    raise ValueError('Unsupported getter expression '+kind)
def render(values):
    return '''// SPDX-License-Identifier: MIT
// Generated by generate.py from public int256 constant declarations.
include "../raw-tree/Connection.dfy"

module CorePublicGetters {
  import opened AbiFrames
  import Words = ResolutionWords
  datatype Getter = LEN | PAYLOAD

  function Signed(g: Getter): int {
    if g == LEN then %s else %s
  }
  function Expected(g: Getter): int { -(Words.Limit()/2 as int) + (if g == LEN then 0 else 1) }
  function Data(g: Getter): seq<Byte> { Word((Signed(g) %% Words.Limit()) as nat) }
  ghost method Source(g: Getter) returns (data: seq<Byte>)
    ensures Signed(g) == Expected(g)
    ensures data == Data(g)
    ensures |data| == 32 && ReadNat(data) == (Expected(g)+Words.Limit()) as nat
  {
    var value := Signed(g);
    data := Word((value %% Words.Limit()) as nat);
    Words.PowerConstants();
    NatBytesRoundTrip((value %% Words.Limit()) as nat,32);
  }
}
''' % (values['LEN'],values['PAYLOAD'])
def main():
    p=argparse.ArgumentParser();p.add_argument('--solc',type=Path,required=True);p.add_argument('--check',action='store_true');a=p.parse_args()
    assert '0.8.36+commit.8a079791' in subprocess.check_output([str(a.solc),'--version'],text=True)
    names=['contracts/Assertions.sol','contracts/lib/AbiCodec.sol','contracts/lib/ERC8211.sol']
    texts={name:(ROOT/name).read_text() for name in names}
    req={'language':'Solidity','sources':{n:{'content':s} for n,s in texts.items()},'settings':{'evmVersion':'cancun','outputSelection':{'*':{'':['ast'],'*':['abi']}}}}
    proc=subprocess.run([str(a.solc),'--standard-json'],input=json.dumps(req),text=True,capture_output=True,check=True)
    out=json.loads(proc.stdout);assert not any(x['severity']=='error' for x in out.get('errors',[]))
    ast=next(n for n in out['sources'][names[0]]['ast']['nodes'] if n['nodeType']=='ContractDefinition' and n['name']=='Assertions')
    declarations=[n for n in ast['nodes'] if n['nodeType']=='FunctionDefinition' and n['visibility'] in ['public','external']]
    assert len(declarations)==15 and all(n['kind']=='function' and n['stateMutability']=='view' for n in declarations)
    constants={n['name']:n for n in ast['nodes'] if n['nodeType']=='VariableDeclaration' and n['visibility']=='public'}
    assert set(constants)=={'LEN','PAYLOAD'}
    values={}
    for name,node in constants.items():
        assert node['constant'] and node['stateVariable'] and node['typeName']['name']=='int256'
        values[name]=integer(node['value'])
    abi=out['contracts'][names[0]]['Assertions']['abi'];functions=[x for x in abi if x['type']=='function']
    # Exact signatures prevent an added overload or unmodeled public entry from passing.
    expected=json.loads((HERE/'inventory.json').read_text())
    actual={signature(x):{'outputs':[canonical(t) for t in x['outputs']],'mutability':x['stateMutability']} for x in functions}
    assert actual=={name:{k:v for k,v in item.items() if k!='proofCase'} for name,item in expected.items()}, ('Public ABI drift',actual)
    cases={('LEN',0):'Getter.LEN',('PAYLOAD',0):'Getter.PAYLOAD',('assertParam',1):'Explicit.DefaultOne',('assertParam',2):'Explicit.AssertOne',('assertBatch',1):'Explicit.DefaultBatch',('assertBatch',2):'Explicit.AssertBatch',('chain',2):'Explicit.Chain',('cond',3):'Explicit.Cond',('gather',1):'Explicit.Gather',('get',4):'Explicit.Get',('isValid',1):'Explicit.IsValid',('nav',3):'Explicit.Nav',('orElse',2):'Explicit.OrElse',('pick',2):'Explicit.Pick',('read',3):'Explicit.Read',('resolve',1):'Explicit.Resolve',('revertData',2):'Explicit.Probe'}
    assert len(cases)==17 and len(set(cases.values()))==17
    assert all(expected[signature(x)]['proofCase']==cases[(x['name'],len(x['inputs']))] for x in functions)
    assert len(actual)==17
    generated=render(values);dest=HERE/'Getters.generated.dfy'
    if a.check: assert dest.read_text()==generated, 'Generated getter drift'
    else: dest.write_text(generated)
    print(json.dumps({'status':'passed','publicFunctions':len(actual),'explicitFunctions':len(declarations),'getters':values,'abi':expected,'sourceSha256':{n:hashlib.sha256(s.encode()).hexdigest() for n,s in texts.items()}},indent=2))
if __name__=='__main__':main()
