// SPDX-License-Identifier: MIT
// Complete affected source closures; this entry point grants no source acceptance.
include "HelperModelBridge.dfy"
include "../../source/assertions/core/completion/Connection.dfy"
include "../../source/collections/value-codec/Connection.dfy"
include "../../source/collections/value-entry/Connection.dfy"
include "../../source/collections/value-pairs/Inverses.dfy"
include "../../source/collections/value-search/Connection.dfy"
include "../../source/collections/value-sort-entry/Connection.dfy"
include "../../source/collections/value-structure/Connection.dfy"
include "../../source/collections/value-unique/Classes.dfy"
include "../../source/collections/word-apply/Connection.dfy"
include "../../source/collections/word-fold-entry/Connection.dfy"
include "../../source/collections/word-layout/Connection.dfy"
include "../../source/collections/word-scans/Connection.dfy"
include "../../source/collections/word-sort/Connection.dfy"
include "../../source/collections/word-unique/Connection.dfy"
include "../../source/expressions/tree/Connection.dfy"
include "../../source/expressions/validation/Connection.dfy"
include "../../source/operations/fixed-point-accuracy/Kernel.dfy"
include "../../source/operations/fixed-point/Connection.dfy"
include "../../source/operations/modular-power/Connection.dfy"
include "../../source/operations/scalars/Connection.dfy"
include "../../source/operations/scaled-power/Connection.dfy"
include "../../source/operations/tuple-encode/Connection.dfy"
module EvmAdoptionSourceClosure1 {}
