// Explorer source verification: submits the solc standard-JSON input bundled
// with the site (generated by scripts/export-deploy-artifact.mjs from the
// exact compile that produced the canonical bytecode) to the target chain
// through the Etherscan V2 multichain API (one API key for every supported
// explorer). Self-contained on purpose: it works even on the very first
// deployment of a contract, when no other chain has a verified copy yet.

import { DEPLOYED_CONTRACTS } from "./shared";

const V2_API = "https://api.etherscan.io/v2/api";

export type VerifyProgress =
  | "submitting"
  | "polling"
  | "verified"
  | "already-verified";

interface EtherscanResponse {
  status: string;
  message: string;
  result: unknown;
}

async function etherscanGet(
  chainId: number,
  apiKey: string,
  params: Record<string, string>,
): Promise<EtherscanResponse> {
  const url = new URL(V2_API);
  url.searchParams.set("chainid", String(chainId));
  url.searchParams.set("apikey", apiKey);
  for (const [key, value] of Object.entries(params)) {
    url.searchParams.set(key, value);
  }
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Etherscan API HTTP ${response.status}`);
  return (await response.json()) as EtherscanResponse;
}

let supportedChainsPromise: Promise<Set<number>> | null = null;

/** Chain ids covered by the Etherscan V2 multichain API (cached, keyless). */
export function getEtherscanChains(): Promise<Set<number>> {
  supportedChainsPromise ??= (async () => {
    const response = await fetch("https://api.etherscan.io/v2/chainlist");
    if (!response.ok) throw new Error(`chainlist HTTP ${response.status}`);
    const data = (await response.json()) as {
      result: { chainid: string; status: number }[];
    };
    return new Set(data.result.map((c) => Number(c.chainid)));
  })();
  supportedChainsPromise.catch(() => {
    supportedChainsPromise = null;
  });
  return supportedChainsPromise;
}

/** True when the source of BOTH contracts is verified on the chain's explorer. */
export async function isContractVerified(
  chainId: number,
  apiKey: string,
): Promise<boolean> {
  for (const contract of DEPLOYED_CONTRACTS) {
    const response = await etherscanGet(chainId, apiKey, {
      module: "contract",
      action: "getabi",
      address: contract.address,
    });
    if (/missing\/invalid api key/i.test(String(response.result))) {
      throw new Error(String(response.result));
    }
    if (response.status !== "1") return false;
  }
  return true;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

/** Verifies one contract on the target chain from the bundled compiler input. */
async function verifyOne(
  targetChainId: number,
  apiKey: string,
  address: string,
  contractLabel: string,
  bundled: { contractName: string; compilerVersion: string; input: unknown },
  onProgress: (step: VerifyProgress) => void,
): Promise<"verified" | "already-verified"> {
  onProgress("submitting");
  const url = new URL(V2_API);
  url.searchParams.set("chainid", String(targetChainId));
  url.searchParams.set("apikey", apiKey);
  const body = new URLSearchParams({
    module: "contract",
    action: "verifysourcecode",
    contractaddress: address,
    codeformat: "solidity-standard-json-input",
    sourceCode: JSON.stringify(bundled.input),
    contractname: bundled.contractName,
    compilerversion: bundled.compilerVersion,
    constructorArguements: "",
  });
  const submitResponse = await fetch(url, { method: "POST", body });
  if (!submitResponse.ok) {
    throw new Error(`Etherscan API HTTP ${submitResponse.status}`);
  }
  const submitted = (await submitResponse.json()) as EtherscanResponse;
  const submitResult = String(submitted.result);
  if (submitted.status !== "1") {
    if (/already verified/i.test(submitResult)) return "already-verified";
    throw new Error(
      `Verification submission failed for ${contractLabel}: ${submitResult}`,
    );
  }

  onProgress("polling");
  const guid = submitResult;
  for (let attempt = 0; attempt < 30; attempt++) {
    await sleep(4000);
    const check = await etherscanGet(targetChainId, apiKey, {
      module: "contract",
      action: "checkverifystatus",
      guid,
    });
    const result = String(check.result);
    if (/^pass/i.test(result)) return "verified";
    if (/already verified/i.test(result)) return "already-verified";
    if (/^fail/i.test(result)) {
      throw new Error(`Verification failed for ${contractLabel}: ${result}`);
    }
    // "Pending in queue" / "Unable to locate ContractCode" — keep polling
    // while the explorer indexes the freshly deployed bytecode.
  }
  throw new Error(
    `Verification of ${contractLabel} timed out — it may still complete; ` +
      "check the explorer in a few minutes.",
  );
}

/**
 * Verifies BOTH contracts (Assertions + Operators) on the target chain from
 * the compiler inputs bundled with the site. Resolves with "already-verified"
 * only when every contract was already verified, "verified" otherwise; throws
 * on failure.
 */
export async function verifyContracts(
  targetChainId: number,
  apiKey: string,
  onProgress: (step: VerifyProgress) => void,
): Promise<"verified" | "already-verified"> {
  // Loaded lazily: the module embeds the full Solidity sources.
  const { VERIFICATION_INPUTS } = await import("../../lib/verification-inputs");
  let allAlready = true;
  for (const contract of DEPLOYED_CONTRACTS) {
    const result = await verifyOne(
      targetChainId,
      apiKey,
      contract.address,
      contract.name,
      VERIFICATION_INPUTS[contract.key],
      onProgress,
    );
    if (result !== "already-verified") allAlready = false;
  }
  return allAlready ? "already-verified" : "verified";
}
