// SPDX-License-Identifier: MIT
// GENERATED by generate.py from solc 0.8.36+commit.8a079791 AST. Do not edit.
// Source SHA-256: 485f0d49f35528cc4c9be7767c631be6903ff57b5cb95bcbb25d6cd04ce5fed6
include "ByteSemantics.dfy"

module AbiBytesSource {
  import opened AbiFrames
  import opened AbiEncoding
  import opened AbiValidation
  import opened AbiByteSemantics

  ghost method ReadWord(v: seq<Byte>, p: nat) returns (r: Outcome)
    requires Uint(|v|) && Uint(p)
    ensures r == WordSpec(v,p)
    ensures r.Ok? ==> Uint(r.used)
  {
    // solc AST 946 @ 20227:67:0
    var tmp1: bool := (p <= |v|);
    if tmp1 {
      var tmp2: int := |v| - p;
      if !Uint(tmp2) { r := Panic(17); return; }
      tmp1 := (tmp2 >= 32);
    }
    if !(tmp1) {
      r := Invalid(p); return;
    }
    // solc AST 947 @ 20304:62:0
    assert p+32 <= |v|;
    BytesNatRoundTrip(v[p..p+32]);
    r := Ok(ReadNat(v[p..p+32])); return;
  }
  ghost method BytesBody(v: seq<Byte>, p: nat) returns (r: Outcome)
    requires Uint(|v|) && Uint(p)
    ensures r == BodySpec(v,p)
    ensures r.Ok? ==> p+r.used <= |v|
  {
    // solc AST 1245 @ 25067:39:0
    if !((p <= |v|)) {
      r := Invalid(p); return;
    }
    // solc AST 1656 @ 27416:31:0
    var tmp3 := ReadWord(v,p);
    if !tmp3.Ok? { r := tmp3; return; }
    var n: int := tmp3.used;
    RoundedExtent(n);
    // solc AST 1669 @ 27457:48:0
    var tmp4: int := |v| - p;
    if !Uint(tmp4) { r := Panic(17); return; }
    var tmp5: int := tmp4 - 32;
    if !Uint(tmp5) { r := Panic(17); return; }
    if !((n <= tmp5)) {
      r := Invalid(p); return;
    }
    // solc AST 1680 @ 27515:35:0
    var tmp6: int := n + 31;
    if !Uint(tmp6) { r := Panic(17); return; }
    if 32 == 0 { r := Panic(18); return; }
    var tmp7: int := tmp6 / 32;
    if !Uint(tmp7) { r := Panic(17); return; }
    var tmp8: int := tmp7 * 32;
    if !Uint(tmp8) { r := Panic(17); return; }
    var padded: int := tmp8;
    assert padded == n+Padding(n);
    // solc AST 1693 @ 27560:53:0
    var tmp9: int := |v| - p;
    if !Uint(tmp9) { r := Panic(17); return; }
    var tmp10: int := tmp9 - 32;
    if !Uint(tmp10) { r := Panic(17); return; }
    if !((padded <= tmp10)) {
      r := Invalid(p); return;
    }
    // solc AST 1699 @ 27623:28:0
    var tmp11: int := padded - n;
    if !Uint(tmp11) { r := Panic(17); return; }
    var padding: int := tmp11;
    // solc AST 1759 @ 27661:336:0
    var tmp12: bool := (padding != 0);
    if tmp12 {
      var tmp13: int := p + padded;
      if !Uint(tmp13) { r := Panic(17); return; }
      var tmp14 := ReadWord(v,tmp13);
      if !tmp14.Ok? { r := tmp14; return; }
      var tmp15: int := 32 - padding;
      if !Uint(tmp15) { r := Panic(17); return; }
      var tmp16: int := tmp15 * 8;
      if !Uint(tmp16) { r := Panic(17); return; }
      assert 0 <= padding < 32;
      PaddingMask(v,p,n,padded);
      tmp12 := ((tmp14.used % Pow256(padding)) != 0);
    }
    if tmp12 {
      // solc AST 1758 @ 27762:235:0
      // solc AST 1757 @ 27864:123:0
      // solc AST 1731 @ 27869:13:0
      var i: int := n;
      while i < padded
        invariant n <= i <= padded
        invariant Uint(i)
        invariant ZeroRegion(v,p+32+n,p+32+i)
        decreases padded-i
      {
        // solc AST 1756 @ 27901:86:0
        // solc AST 1755 @ 27919:53:0
        var tmp17: int := p + 32;
        if !Uint(tmp17) { r := Panic(17); return; }
        var tmp18: int := tmp17 + i;
        if !Uint(tmp18) { r := Panic(17); return; }
        if tmp18 < 0 || tmp18 >= |v| { r := Panic(50); return; }
        var tmp19: int := p + 32;
        if !Uint(tmp19) { r := Panic(17); return; }
        var tmp20: int := tmp19 + i;
        if !Uint(tmp20) { r := Panic(17); return; }
        if !((v[tmp18] == 0)) {
          FirstDirtyAt(v,p+32+n,p+32+padded,p+32+i);
          r := Invalid(tmp20); return;
        }
        // solc AST 1737 @ 27896:3:0
        var tmp21: int := i + 1;
        if !Uint(tmp21) { r := Panic(17); return; }
        i := tmp21;
      }
    }
    // solc AST 1763 @ 28006:18:0
    var tmp22: int := 32 + padded;
    if !Uint(tmp22) { r := Panic(17); return; }
    FirstDirtyCharacterization(v,p+32+n,p+32+padded);
    r := Ok(tmp22); return;
  }
  ghost method ValidateBytes(v: seq<Byte>) returns (r: Outcome)
    requires Uint(|v|)
    ensures r == ValidationSpec(v)
  {
    // solc AST 1179 @ 23505:51:0
    var tmp23 := ReadWord(v,0);
    if !tmp23.Ok? { r := tmp23; return; }
    if !((tmp23.used == 32)) {
      r := Invalid(0); return;
    }
    // solc AST 1193 @ 23566:55:0
    var tmp24 := BytesBody(v,32);
    if !tmp24.Ok? { r := tmp24; return; }
    var tmp25: int := 32 + tmp24.used;
    if !Uint(tmp25) { r := Panic(17); return; }
    var end: int := tmp25;
    // solc AST 1202 @ 23631:43:0
    if !((end == |v|)) {
      r := Invalid(end); return;
    }
    r := Ok(0);
  }
}
