#!/usr/bin/env python3
"""Faithful exact terminal controls with whole healthy and changed caller bridges.

Every bridge copies all original caller admission and Good conditions unchanged.
Only actual code/Good state definitions follow the one changed runtime byte. The
changed bridges use real memory lemmas and never call an invalid caller theorem.
"""
import argparse,json
from pathlib import Path
SCALAR_CONTROL = '// SPDX-License-Identifier: MIT\n// Exact complete scalar terminal frame and unchanged32-byte return oracle.\ninclude "MACHINE"\nmodule FoldScalarTerminalWitness {\n  import opened BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  predicate Frame(state: State,packet: seq<Byte>) {\n    state.Running? && state.pc == 498 && 2 <= |state.stack| <= 1024 &&\n    var size: nat := state.stack[|state.stack|-2];\n    var off: nat := state.stack[|state.stack|-1];\n    size == WIDTH && |packet| == 32 && off+32 <= |state.memory| && state.memory[off..off+32] == packet\n  }\n  lemma Terminal(code: seq<Byte>,destinations: set<nat>,state: State,packet: seq<Byte>,value: Word,data: seq<Byte>)\n    requires 498 < |code| && code[498] == OPCODE && Frame(state,packet)\n    ensures var next := Step(code,destinations,state,value,data); next == Returned(packet)\n  {\n    hide G.Grow();\n    var size: nat := state.stack[|state.stack|-2];\n    var off: nat := state.stack[|state.stack|-1];\n    assert Fetch(code,498) == Op(OPCODE,499,0);\n    if WIDTH == 32 { assert G.Grow(state.memory,off+32) == state.memory by { reveal G.Grow(); } }\n    reveal Step();\n    assert |G.Grow(state.memory,off+size)[off..off+size]| == size;\n  }\n}\n'
CALLBACK_CONTROL = '// Exact terminal oracle over the complete actual pre-step frame.\ninclude "MACHINE"\nmodule FoldCallbackTerminalWitness {\n  import opened BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  predicate Frame(state: State,packet: seq<Byte>) {\n    state.Running? && state.pc == 1122 && 2 <= |state.stack| <= 1024 &&\n    var size: nat := state.stack[|state.stack|-2];\n    var off: nat := state.stack[|state.stack|-1];\n    off+size <= |state.memory| && state.memory[off..off+size] == packet\n  }\n  lemma Terminal(code: seq<Byte>,destinations: set<nat>,state: State,packet: seq<Byte>,value: Word,data: seq<Byte>)\n    requires 1122 < |code| && code[1122] == 253 && Frame(state,packet)\n    ensures var next := Step(code,destinations,state,value,data); next == Reverted(packet)\n  {\n    hide G.Grow();\n    var size: nat := state.stack[|state.stack|-2];\n    var off: nat := state.stack[|state.stack|-1];\n    assert Fetch(code,1122) == Op(253,1123,0);\n    assert G.Grow(state.memory,off+size) == state.memory by { reveal G.Grow(); }\n    reveal Step();\n  }\n}\n'
CALLBACK_BRIDGE = 'include "HealthyTerminal.dfy"\ninclude "AFTER"\nmodule FoldCallbackTerminalBridge {\n  import opened BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  import A = BytecodeFoldCallbackFailedAfter\n  import T = FoldCallbackTerminalWitness\n  import M = BytecodeApplyCallbackFailedControlMemory\n  import H = BytecodeApplyCallbackFailedMemory\n  import CL = BytecodeFoldCallbackLengthScalar\n  lemma Bridge(code: seq<Byte>,state: State,data: seq<Byte>,mem: seq<Byte>,prefix: seq<Word>,domain: nat,target: Word,ptr: Word,index: Word,gasBefore: Word,receipt: Word,free: Word,payload: seq<Byte>,reason: seq<Byte>,value: Word)\n    requires A.Matches(code) && A.Admitted(data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value) && A.Good(20,state,data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value)\n    ensures 1122 < |code| && code[1122] == 253 && T.Frame(state,H.Packet(CL.Operation(domain),index,target,payload,reason))\n  {\n    hide G.Grow();hide M.Heap();hide H.Packet();hide H.Head();hide H.First();hide H.Offset();hide H.Final();hide DataWord();hide ShiftRight();\n    A.Admission(data,mem,prefix,domain,target,ptr,index,gasBefore,receipt,free,payload,reason,value);\n    M.Info(mem,ptr,receipt,free,CL.Operation(domain),index,target,payload,reason,9);\n    reveal A.Matches();reveal A.Good();\n    assert state == Running(1122,prefix+[16553,target,ptr,index,0,gasBefore,0,receipt,Round32(|payload|)+Round32(|reason|)+260,free],M.Heap(mem,ptr,receipt,free,CL.Operation(domain),index,target,payload,reason,9));\n    assert H.End(free,payload,reason) == free+Round32(|payload|)+Round32(|reason|)+260;\n    assert G.Grow(state.memory,H.End(free,payload,reason)) == state.memory by { reveal G.Grow(); }\n    M.HeapProjection(mem,ptr,receipt,free,CL.Operation(domain),index,target,payload,reason,9);\n    H.FinalBytes(mem,ptr,receipt,free,CL.Operation(domain),index,target,payload,reason);\n    assert state.memory[free..H.End(free,payload,reason)] == H.Packet(CL.Operation(domain),index,target,payload,reason);\n  }\n}\n'
CONFIG = {
 'scalar-return-size-33':dict(pc=612,before=32,after=33,terminalPc=498,healthyOp=243,changedOp=243,width=33,source='formal/bytecode/word-fold/scalar-return/Range.generated.dfy',method='Advance51',module='BytecodeFoldScalarReturnRange',owner='FoldScalarTerminalWitness',bridge='FoldScalarTerminalBridge',packet='G.Encode(word,32)',oracle='Returned(packet)'),
 'successful-return-is-revert':dict(pc=498,before=243,after=253,terminalPc=498,healthyOp=243,changedOp=253,width=32,source='formal/bytecode/word-fold/scalar-return/Words.generated.dfy',method='Advance52',module='BytecodeFoldScalarReturnWords',owner='FoldScalarTerminalWitness',bridge='FoldScalarTerminalBridge',packet='G.Encode(word,32)',oracle='Returned(packet)'),
 'callback-error-is-return':dict(pc=1122,before=253,after=243,terminalPc=1122,healthyOp=253,changedOp=243,width=None,source='formal/bytecode/word-fold/callback-failed-repair-v2/After.generated.dfy',method='Advance20',module='BytecodeFoldCallbackFailedAfter',owner='FoldCallbackTerminalWitness',bridge='FoldCallbackTerminalBridge',packet='H.Packet(CL.Operation(domain),index,target,payload,reason)',oracle='Reverted(packet)')}
def caller_block(file,method):
 s=Path(file).read_text();start=s.index('  lemma '+method+'(');end=s.index('\n  ',s.index('\n  }',start)+1);return s[start:end]
def signature(block,method):
 return block[:block.index('    ensures')].replace('  lemma '+method+'(','  lemma Bridge(').replace('Matches(code)','A.Matches(code)').replace('Admitted(','A.Admitted(').replace('Good(','A.Good(')
def files(root,work,runtime,name):
 root,work=Path(root).resolve(),Path(work).resolve();config=CONFIG[name]
 code=bytes.fromhex(json.loads((root/'artifacts/contracts/Collections.sol/Collections.json').read_text())['deployedBytecode'][2:]);changed=Path(runtime).read_bytes();work_code=bytes.fromhex(json.loads((work/'artifacts/contracts/Collections.sol/Collections.json').read_text())['deployedBytecode'][2:]);assert work_code==changed and len(code)==len(changed)and[(i,a,b)for i,(a,b)in enumerate(zip(code,changed))if a!=b]==[(config['pc'],config['before'],config['after'])],'Exact terminal candidate runtime drift'
 blocks={label:caller_block(base/config['source'],config['method'])for label,base in [('Healthy',root),('Changed',work)]};signatures={label:signature(block,config['method'])for label,block in blocks.items()};assert signatures['Healthy']==signatures['Changed'],'Fault parser restricted baseline admitted callers'
 result={}
 for label,base in [('Healthy',root),('Changed',work)]:
  op=config['healthyOp']if label=='Healthy'else config['changedOp'];width=32 if label=='Healthy'else config['width'];machine=str(base/'formal/bytecode/scans/Machine.dfy')
  if name=='callback-error-is-return':
   control=CALLBACK_CONTROL.replace('MACHINE',machine).replace('code[1122] == 253','code[1122] == '+str(op)).replace('Op(253,1123,0)','Op('+str(op)+',1123,0)')
   bridge=CALLBACK_BRIDGE.replace('include "HealthyTerminal.dfy"','include "'+label+'Terminal.dfy"').replace('AFTER',str(base/config['source'])).replace('code[1122] == 253','code[1122] == '+str(op));assert signatures[label]in bridge
  else:
   control=SCALAR_CONTROL.replace('MACHINE',machine).replace('WIDTH',str(width)).replace('OPCODE',str(op))
   state=next(line for line in blocks[label].splitlines()if'assert state =='in line)
   bridge='// SPDX-License-Identifier: MIT\ninclude "'+label+'Terminal.dfy"\ninclude "'+str(base/config['source'])+'"\nmodule FoldScalarTerminalBridge {\n  import opened BytecodeScanMachine\n  import G = BytecodeGetterMachine\n  import MR = BytecodeScanRepresentation\n  import A = '+config['module']+'\n  import T = FoldScalarTerminalWitness\n'+signatures[label]+'    ensures 498 < |code| && code[498] == '+str(op)+' && T.Frame(state,G.Encode(word,32))\n  {\n    hide G.Encode();hide G.Grow();hide Store();hide Load();hide G.BitAnd();hide G.Shift();\n    reveal A.Matches();reveal A.Good();\n'+state+'\n    MR.StoredWord(mem,free,word);\n    assert |Store(mem,free,word)| >= free+32;\n  }\n}\n'
  result[label+'Terminal.dfy']=control;result[label+'Bridge.dfy']=bridge
 return result
def main():
 p=argparse.ArgumentParser();p.add_argument('--root',type=Path,required=True);p.add_argument('--work',type=Path,required=True);p.add_argument('--runtime',type=Path,required=True);p.add_argument('--name',choices=CONFIG,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=False)
 for name,body in files(a.root,a.work,a.runtime,a.name).items():(a.output/name).write_text(body)
 print('Generated complete healthy/changed terminal owners and unchanged-admission packet/frame bridges')
if __name__=='__main__':main()
